### ISSUE TITLE
failed to build from git

### ISSUE THREAD

**Issue by kemin711** [rcaelers/workrave#100]
autoreconf -fi
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:957: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:957: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:957: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
configure.ac:139: installing './compile'
configure.ac:30: installing './missing'
backend/src/Makefile.am: installing './depcomp'

configure error, showing the last few lines:

config.status: executing libtool commands
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
config.status: executing po/stamp-it commands
config.status: error: po/Makefile.in.in was not created by intltoolize.

**Comment by flooreeda** [comment]
I was able to get around this configure error by executing the following command prior to ./configure:
`intltoolize --automake --copy --force`

So your build steps would look something like this:
```
autoreconf -if
intltoolize --automake --copy --force
./configure
make
make install
```

I have Workrave running on my Mac; however, it is not stable. The program crashes when it issues a notification to take a break. It also doesn't appear to be counting keystrokes or mouse clicks.

**Comment by kemin711** [comment]
If using autogen scriipt, then the make is fine.
