### ISSUE TITLE
Impossible to build with GTK3 and without introspection

### ISSUE THREAD

**Issue by p-himik** [rcaelers/workrave#112]
**To Reproduce**
1. Configure with
```
--disable-gsettings --disable-gconf --enable-gnome3 \
--disable-indicator --enable-dbus --enable-gstreamer \
--disable-xfce --disable-mate --enable-pulse \
--disable-debug --disable-distribution --enable-experimental \
--enable-exercises --disable-tests --disable-tracing --enable-xml
```
2. Run `make`

**Expected behavior**
Should be built just fine.

**Actual behavior**
Fails with
```
libtool: link: gcc -shared  -fPIC -DPIC  v5/.libs/libworkrave_applet_la-WorkraveApplet.o .libs/libworkrave_applet_la-workrave-gnome-applet-generated.o   -lpanel-applet -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -L./../../common/src -lworkrave-private-1.0  -pthread -g -O2   -pthread -Wl,-soname -Wl,libworkrave-applet.so -o .libs/libworkrave-applet.so
/usr/bin/x86_64-linux-gnu-ld: cannot find -lworkrave-private-1.0
collect2: error: ld returned 1 exit status
Makefile:637: recipe for target 'libworkrave-applet.la' failed
```

Enabling indicator makes it buildable again.

**Linux:**
 - Distribution: Ubuntu
 - Distribution Version: 18.04.1
 - Desktop Environment: Gnome 3
 - Workrave Version: commit f1f589d23eaed941a441d0757f8deb74886b025e

**Comment by rcaelers** [comment]
I haven't been able to reproduce this problem. Workrave always checks for introspection, even when the Unity indicator is disabled. Could you please attach you config.log?

**Comment by p-himik** [comment]
I have no idea what changed, but I couldn't reproduce it on the latest master. Maybe something also has changed in my environment, I don't have a clue.
