### ISSUE TITLE
Chrome on Windows warns about Workrave 1.10 being incompatible

### ISSUE THREAD

**Issue by SanderGit** [rcaelers/workrave#113]
**Describe the bug**
Chrome 68.0.3440.106 on Windows warns that Workrave is an incompatible appllication.
This has been announced here and is apparently related to code injection:
https://www.bleepingcomputer.com/news/google/google-chrome-showing-alerts-about-incompatible-applications/

**To Reproduce**
1. Start Chrome
2. Notice that it opens at chrome://settings/incompatibleApplications
3. See error

**Expected behavior**
Workrave not to cause warnings in Chrome

**Screenshots**
![workrave_chrome](https://user-images.githubusercontent.com/5788984/44654012-97461d80-a9f0-11e8-874a-9d9041a1b0d8.png)

** Windows (please complete the following information in case you encountered the bug on Windows):
 - Windows Version: 10 (build 1803)
 - Workrave Version: 1.10

**Comment by rcaelers** [comment]
It seems Chrome version 87.0.4280.141 no longer gives this warning. At least not on my computer:

<img width="1247" alt="Chrome-clean-up-computer" src="https://user-images.githubusercontent.com/80881/104959065-9e12c800-59d1-11eb-8605-22e6746af12b.png">

Workrave uses global hooks for monitoring keyboard/mouse activity when the alternate monitor is enabled in the settings. These global hooks are also used to lock keyboard and mouse during breaks. These global hooks indeed inject code in the event loop of other applications. We tried different methods to block keyboard/mouse in the past (e.g. using a transparent full screen always-on-top window), but using global hooks was the most reliable one.
