### ISSUE TITLE
Making static release archives available

### ISSUE THREAD

**Issue by kmosiejczuk** [rcaelers/workrave#117]
**Describe the bug**
The tagged releases available by following Github's "Creating releases" are dynamically generated and can (and have) change. This breaks checksums. 

**To Reproduce**
The Github tarballs currently available were produced by the Github "creating releases" process. It generates a tarball on the fly when a user downloads. More background can be found at: https://marc.info/?l=openbsd-misc&m=153492430016386&w=2

When Github changes how they are generated, the OpenBSD port (which I'm attempting to update from 1.10.1) will break, as it verifies the checksum of the source tarball. 

**Expected behavior**
Checksums will match because we are downloading a static tarball.

**Comment by rcaelers** [comment]
Starting version 1.10.30, the build automation should automatically upload a source tarball.
