### ISSUE TITLE
[Question] Increase the number of exercises to choose in the brakes

### ISSUE THREAD

**Issue by jonnyforestGIS** [rcaelers/workrave#119]
Hi,
i want to help and put more exercices. how can i add and update the exercises? With more exercises images and descriptions?
It's is possible and animated gif instead static .png images?
This is one of the examples that i want to put.

https://www.instagram.com/p/Bo1YIQalBGA/

https://www.instagram.com/p/Bm0xdMElwwE/

Regards,
João

**Comment by rcaelers** [comment]
Workrave's exercises are defined in XML: https://github.com/rcaelers/workrave/blob/branch_v1_10/frontend/plugin/exercises/common/share/exercises.xml.in

You can easily extend it. Not sure if the Gtk+ library we use supports animated png.

I'm closing this question. Looking forward to a pull request :-) Let me know if you have further questions.
