### ISSUE TITLE
Feature request: get remaining daily limit from command-line

### ISSUE THREAD

**Issue by orschiro** [rcaelers/workrave#126]
Dear @rcaelers,

Would it be possible to add a command-line option for `workrave` to return the remaining daily limit using the Linux command-line? 🙂👍

Thanks!

![image](https://user-images.githubusercontent.com/170947/54536070-4a2b9800-4990-11e9-8abc-751c16bdb2e5.png)

**Comment by rcaelers** [comment]
On Linux you can use DBus to get the elapsed time of a breaks, and the configured duration:

$ gdbus call -e -d org.workrave.Workrave -o /org/workrave/Workrave/Core -m org.workrave.CoreInterface.GetTimerElapsed 'dailylimit'
(2287,)

$ gdbus call -e -d org.workrave.Workrave -o /org/workrave/Workrave/Core -m org.workrave.ConfigInterface.GetInt 'timers/daily_limit/limit'
(14400, true)

So remaining = 14400 - 2287 seconds. Currently not supported on Windows.
(Note that configuration uses slightly different breaks names....)

I will extend the CoreInterface with a function to get the remaining time until next break directory.

**Comment by orschiro** [comment]
This is great, thanks Rob! 🙂

-

**Comment by rcaelers** [comment]
In 1.10.31:

$ gdbus call -e -d org.workrave.Workrave -o /org/workrave/Workrave/Core -m org.workrave.CoreInterface.GetTimerRemaining 'dailylimit'
(14394,)

**Comment by orschiro** [comment]
Sweet, thanks Rob! 🙂👍

-
