### ISSUE TITLE
Not working KDE

### ISSUE THREAD

**Issue by troe** [rcaelers/workrave#127]
Hi, I installed the program through the ppa:rob-caelers/workrave PPA repository, the installation was successful, then, when the program was opened, only 2 icons appeared in the system tray, and the program window itself did not open, i.e. program settings are not available, when you right-click, settings or any actions with the program are also not available, but the program itself works, as far as I can tell, i.e. notifications about breaks come, apparently some standard break patterns

Screenshot
![Plasma_112](https://user-images.githubusercontent.com/1324558/54660734-c1cd0480-4b01-11e9-9995-dbf281937a0a.png)

Distribution: Kubuntu
Distribution Version: 16.04.6
Desktop Environment: KDE Plasma 5.8.9
Workrave Version: 1.10.23

**Comment by troe** [comment]
Distribution: Kubuntu
Distribution Version: 18.04
Desktop Environment: KDE Plasma 5.12.7
Workrave Version: 1.10.23

In Kubuntu 18.04 it works, it is possible to open the settings, but the tray has 2 icons, one has an icon, and the other does not: one has the inscription "workrave" on it, and the other has "Workrave Tray Icon"

**Comment by IsaakGroepT** [comment]
> Distribution: Kubuntu
> Distribution Version: 18.04
> Desktop Environment: KDE Plasma 5.12.7
> Workrave Version: 1.10.23
> 
> In Kubuntu 18.04 it works, it is possible to open the settings, but the tray has 2 icons, one has an icon, and the other does not: one has the inscription "workrave" on it, and the other has "Workrave Tray Icon"

True, but it does also temporarily work if you go to settings, user interface > applet and uncheck and check the setting. After a minute or so it disappears again.

Antergos latest KDE

**Comment by rcaelers** [comment]
The two icons problem will be fixed in the next release (1.10.45). See also  #258 for more information.

Workrave does provide an applet for KDE. Fortunately, someone created a KDE applet recently, see https://workrave.org/docs/applets/kde/
