### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by City-busz** [rcaelers/workrave#130]
During the build process, a Python 2 script is used to generate D-Bus binding:
https://github.com/rcaelers/workrave/blob/782d4581eb19d8d0d62e067084512d9a3da3776c/common/bin/dbusgen.py

Since [Python 2 will be retired soon](https://pythonclock.org/), please port this code to Python 3.

**Comment by rcaelers** [comment]
I will backport dbusgen from the next brach to v1.10. This one uses jinja2 instead of cheetah and supports python3.
