### ISSUE TITLE
distribute as AppImage

### ISSUE THREAD

**Issue by Polisson** [rcaelers/workrave#140]
Is it possible to start distribution/packaging as [AppImage](https://appimage.org), if yes, so when?

**Comment by daya** [comment]
Please release an AppImage for this

**Comment by rcaelers** [comment]
I have added support for AppImage in the 'main' / v1.11 branch.
Development snapshots are available from https://workrave.org/snapshots/ (select Workrave 1.11)
Note that v1.11 has seen a lot of internal cleanup/refactoring and may not be very stable at the moment.
