### ISSUE TITLE
Branch `next` does not build.

### ISSUE THREAD

**Issue by kindaro** [rcaelers/workrave#144]
## Description:

`next` branch does not build in an obvious way.

## See for yourself:

    % cd src/workrave-next-gtk3-git/
    % git describe --long
    v1_10_29-655-g36786eb7
    % cd build
    % cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DWITH_UI=Gtk+3 -DWITH_DBUS=false ..
    ...
    % make
    [ 73%] Building CXX object ui/apps/gtkmm/src/CMakeFiles/workrave.dir/unix/UnixGrab.cc.o
    .../src/workrave-next-gtk3-git/ui/apps/gtkmm/src/unix/UnixGrab.cc: In member function ‘virtual void UnixGrab::grab(GdkWindow*)’:
    .../src/workrave-next-gtk3-git/ui/apps/gtkmm/src/unix/UnixGrab.cc:52:9: error: ‘GtkUtil’ has not been declared
       52 |   if (! GtkUtil::running_on_wayland())
          |         ^~~~~~~
    .../src/workrave-next-gtk3-git/ui/apps/gtkmm/src/unix/UnixGrab.cc: In member function ‘virtual void UnixGrab::ungrab()’:
    .../src/workrave-next-gtk3-git/ui/apps/gtkmm/src/unix/UnixGrab.cc:137:9: error: ‘GtkUtil’ has not been declared
      137 |   if (! GtkUtil::running_on_wayland())
          |         ^~~~~~~
    make[2]: *** [ui/apps/gtkmm/src/CMakeFiles/workrave.dir/build.make:544: ui/apps/gtkmm/src/CMakeFiles/workrave.dir/unix/UnixGrab.cc.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:1501: ui/apps/gtkmm/src/CMakeFiles/workrave.dir/all] Error 2
    make: *** [Makefile:152: all] Error 2

## Expected behaviour:

Everything builds fine.

## My solution:

Applying the following patch will lead to the build succeeding:

    % cat GtkUtil.patch
    diff --git a/ui/apps/gtkmm/src/unix/UnixGrab.cc b/ui/apps/gtkmm/src/unix/UnixGrab.cc
    index 6e48f40e..7d055d1d 100644
    --- a/ui/apps/gtkmm/src/unix/UnixGrab.cc
    +++ b/ui/apps/gtkmm/src/unix/UnixGrab.cc
    @@ -49,7 +49,7 @@ UnixGrab::can_grab()
     void
     UnixGrab::grab(GdkWindow *window)
     {
    -  if (! GtkUtil::running_on_wayland())
    +  if (! Platform::running_on_wayland())
         {
           grab_wanted = true;
           if (!grabbed)
    @@ -134,7 +134,7 @@ UnixGrab::grab_internal()
     void
     UnixGrab::ungrab()
     {
    -  if (! GtkUtil::running_on_wayland())
    +  if (! Platform::running_on_wayland())
         {
           grabbed = false;
           grab_wanted = false;

Unfortunately, I still get a segmentation fault when running the program, but that may be for any
other reason.

## My operating system:
Arch Linux, recently updated.

**Comment by rcaelers** [comment]
Thanks for reporting. It seems my Travis build did not properly report build errors... Should be fixed now.

**Comment by kindaro** [comment]
Thank you. Now it builds smoothly.
