### ISSUE TITLE
[enhancement] gnome-shell applet warning

### ISSUE THREAD

**Issue by mattia-b89** [rcaelers/workrave#149]
**Describe the bug**
gnome-shell logs warning about workrave applet; I noticed it when unlock desktop and as well during laptop wake up from stand-by

**To Reproduce**
1. lock/unlock the desktop OR suspend/resume the pc

**Linux (please complete the following information in case you encountered the bug on Linux):**
 - Arch Linux x86_64 
 - Distribution Version: rolling release
 - gnome-shell 3.34.0
 - Workrave 1.10.34

**Comment by rcaelers** [comment]
I checked this with Gnome Shell 3.38.4 on Ubuntu 21.04. I did not see any gnome shell warnings when locking/unlocking the desktop. Do you still see these warnings? If so what warning messages are logged?

**Comment by mattia-b89** [comment]
Fixed upstream
