### ISSUE TITLE
Countdown continues while watching video

### ISSUE THREAD

**Issue by grahamrhay** [rcaelers/workrave#152]
**Describe the bug**

I recently upgraded to v1.10.34, on arch with gnome3, and when I'm watching a video e.g. on youtube, the countdown continues (it didn't before). I found [this](https://issues.workrave.org/show_bug.cgi?id=1002), but reading mode is off.

**To Reproduce**

Run workrave, watch video (stop typing), countdown continues and flashes yellow

**Expected behavior**

Countdown stops

** Linux (please complete the following information in case you encountered the bug on Linux):**
 - Arch (https://www.archlinux.org/packages/community/x86_64/workrave/)
 - Distribution Version: n/a
 - Desktop Environment: Gnome 3.34.1
 - Workrave Version: 1.10.34

I wouldn't be surprised if it was a gnome issue somehow, given how often they break the applet. Let me know if there's anything I can do, to help investigate (I'm hugely grateful for this project, it's saved me a lot of pain.)

**Comment by grahamrhay** [comment]
downgraded to 1.10.31, and the problem remains :(

https://archive.archlinux.org/packages/w/workrave/

actually, looking at those dates, I'm not sure if I even upgraded workrave when the problem began. seems likely to be a gnome issue

**Comment by rcaelers** [comment]
Did you switch from X11 to Wayland> Workrave has limited support for Wayland. Maybe this causes issues somehow.

**Comment by grahamrhay** [comment]
I don't think I switched recently, I've probably been using wayland for some time. but that does seem to solve the issue, thanks!
