### ISSUE TITLE
How to translate the program?

### ISSUE THREAD

**Issue by mfakih294** [rcaelers/workrave#160]
I would like to translate the program to Arabic (a right-to-left language). Which i18n file do I need to edit?

**Comment by rcaelers** [comment]
Workrave uses GNU gettext for dealing with translations. Translating Workrave boils down to providing a translated text for each and every English text used in Workrave. All of the texts to be translated are listed in one file (.po). For each text you need to provide the translation by inserting it in that very same .po file. Translating can be a very tedious job. Luckily there is tooling available to help you. For example, for GNU/Linux, there is kbabel, gtranslator and many others. For Windows, there is poEdit. And for GNU/Emacs, there is the excellent M-x po-mode. So first, you will have to pick any of the above tools, depending on the platform you are working on. Install that tool first, and get acquainted with it. From that point on, you can start translating using the .po files. 

You can find all the i18n files in https://github.com/rcaelers/workrave/blob/branch_v1_10/po.
You can start using an empty template files: https://github.com/rcaelers/workrave/blob/branch_v1_10/po/workrave.pot.

I will close this issue, but please let me know if you have further question.
