### ISSUE TITLE
workrave "always on top" does not appear to work in 3.34

### ISSUE THREAD

**Issue by thoraxe** [rcaelers/workrave#161]
Description of problem:

Version-Release number of selected component (if applicable):
1.10.20-6.fc31

How reproducible:
100%?

Steps to Reproduce:

Actual results:
Clicking any other window results in the status window being behind.

Expected results:
Status window should stay on top

Additional info:
I believe that this also affects the pop-up windows for the timers.

**Describe the bug**
Workrave's user interface settings have a flag for the status window for "always on top"/stays on top. This doesn't seem to have any effect.

**To Reproduce**
1. Go into workrave preferences
2. User Interface -> Status Window
3. Set "the status window stays on top of other windows" checked
4. Click "close"

Clicking any other window results in the status window being behind.

**Expected behavior**
Status window should stay on top

**Screenshots**
N/A

**Linux (please complete the following information in case you encountered the bug on Linux):**
 - Distribution: Fedora
 - Distribution Version: 31
 - Desktop Environment: Gnome 3.34
 - Workrave Version: workrave-1.10.20-6.fc31.x86_64

**Comment by rcaelers** [comment]
Unfortunately, Wayland does not allow applications to make windows always-on-top.

I have disabled the always-on-top settings when Workrave is running under Wayland. Furthermore, right clicking on the window title bar will no longer show the Workrave menu, but the standard window menu. In this menu you can make the window stay on top.

**Comment by ilippert** [comment]
The 

> the standard window menu. In this menu you can make the window stay on

I confirm this works.
I run Fedora 5.8.12-200.fc32.x86_64
with 1.10.44
