### ISSUE TITLE
on scaled screens, blocking input appears "off" screen

### ISSUE THREAD

**Issue by thoraxe** [rcaelers/workrave#162]
**Describe the bug**
I have a 4k monitor but I run Gnome at 200% scaled. When in this mode, the various Workrave pop-ups appear in odd locations.

**To Reproduce**
1. Operate gnome in scaled mode.

When blocking input pop-ups appear, they are off screen to the bottom-right (partially hidden).

When in non-scaled mode, the pop-ups appear centered as expected.

**Expected behavior**
Pop-ups should appear centered on screen.

**Linux (please complete the following information in case you encountered the bug on Linux):**
 - Distribution: Fedora
 - Distribution Version: 31
 - Desktop Environment: Gnome 3.34
 - Workrave Version: workrave-1.10.20-6.fc31.x86_64

**Comment by rcaelers** [comment]
Thanks for the report. Workrave should handle display scaling in the next version.
