### ISSUE TITLE
Non-blocking pop-up never appears centered or remembers where it was

### ISSUE THREAD

**Issue by thoraxe** [rcaelers/workrave#163]
**Describe the bug**
When a non-blocking pop-up appears, it is always at the top-left of the screen, never centered.

**To Reproduce**
1. Configure for non-blocking pop-ups
2. wait for a pop-up

It will always appear at the top left.

**Expected behavior**
Pop-ups should be centered

**Linux (please complete the following information in case you encountered the bug on Linux):**
 - Distribution: Fedora
 - Distribution Version: 31
 - Desktop Environment: Gnome 3.34
 - Workrave Version: workrave-1.10.20-6.fc31.x86_64

**Comment by rcaelers** [comment]
Do you know if you are using Wayland?

**Comment by thoraxe** [comment]
Yes pretty sure Fedora 31 has Wayland enabled.

**Comment by rcaelers** [comment]
I am now opening non-blocking break windows as modal. This should center them when running Mutter (gnome). I doubt this can be solved in general when running Wayland. Wayland does not support absolute positioning of top-level windows.
