### ISSUE TITLE
Menu hot-keys don't work in tray menu

### ISSUE THREAD

**Issue by ryancu7** [rcaelers/workrave#174]
**Describe the bug**
Pressing the key corresponding to an underlined letter in a menu item in the system tray icon's context menu does nothing.

**To Reproduce**
1. Right-click the Workrave icon in the Windows system tray.
2. Press the 'R' key on the keyboard.

**Expected behavior**
Rest break should begin. 

**Windows:**
 - Windows Version: Windows 10 (1909)
 - Workrave Version: 1.10 (from official website)

**Additional note**
Please also change one of the hot-keys for either "Rest break" or "Reading mode" so that they are not both 'R'. As it is, even if hotkeys were working, neither menu option can be chosen by pressing a single key because of the ambiguity.

**Comment by rcaelers** [comment]
This will be fixed in the first Workrave v1.11 release (1.11-alpha1)
