### ISSUE TITLE
Audio or video playing in a browser window prevents taking a break

### ISSUE THREAD

**Issue by ssssam** [rcaelers/workrave#181]
**Describe the bug**
Sometimes Workrave won't take a break, even when there is no keyboard or mouse movement. It seems to be when I have a browser tab focused in Firefox that is playing video or audio.

**To Reproduce**
1. Go to bandcamp.com and put on some nice music
2. Run workrave and wait for the micro-break
3. Break doesn't start even when keyboard and mouse are idle.

**Expected behavior**
The break should start.

** Linux (please complete the following information in case you encountered the bug on Linux):**
 - Distribution: Fedora
 - Distribution Version:  31
 - Desktop Environment: GNOME (Wayland)
 - Workrave Version 1.1.20 (6.fc31)

**Additional context**
I really like Workrave, thanks for maintaining it :)

**Comment by rcaelers** [comment]
Could you please explain what you mean by "break doesn't start"?
Normally Workrave first reminds you to take a break using the small [break reminder window](https://workrave.org/docs/breaks/reminder/). 
When you stop using keyboard and mouse, the reminder window is replaced by the actual break window. Does Workrave still show the break window (but the break is not progressing)? Or does Workrave just remove the reminder window without showing the break window? 
 
Workrave's support for Wayland is poor at the moment. So switching to Xorg may solve the problem.

**Comment by ssssam** [comment]
Workrave shows the break reminder window, but it doesn't show the break window. It's as if I'm moving the keyboard or the mouse, except I'm not.

Sometimes it will show the break window (perhaps when it's already shown 3 reminders), but then the break doesn't progress, instead the window flashes yellow as if I was moving the keyboard and the mouse.

If nobody has spent time polishing the Wayland support then that's probably the cause indeed.

**Comment by mvz** [comment]
I can confirm that this issue also exists on Xorg. The symptoms are the same. I'm using 

- Distribution: Debian
- Distribution Version: Sid
- Desktop Environment: GNOME (Xorg)
- Workrave Version 1.10.43

**Comment by rcaelers** [comment]
I have been able to reproduce this issue on Ubuntu 20.04 running Gnome on Wayland. When I start music playback in bandcamp, Workrave stays 'active' until I stop music playback. Fascinating…

**Comment by rcaelers** [comment]
It seems the behavior of the Gnome idle monitor that is used by Workrave was changed two years ago. When the computer should not to into sleep mode, or when the screensaver should not be activated, idle/active events are inhibited. So Workrave stays active. (see https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/54)

**Comment by mvz** [comment]
Thanks for fixing this, @rcaelers!

**Comment by ssssam** [comment]
I've just testing out this fix and it's now working as expected for me :) :) Thanks! :+1:
