### ISSUE TITLE
There is a FTBFS case when  next branch is UI:Qt5

### ISSUE THREAD

**Issue by kenhys** [rcaelers/workrave#183]
**Describe the bug**

There is a FTBFS case when  next branch is built with UI:Qt5(by default)

```
usr/bin/c++   -DQT_NO_KEYWORDS  -Wall   CMakeFiles/mate-workrave-applet.dir/main-gtk2.c.o  -o workrave-applet  -Wl,-rpath,/root/workrave/build/ui/applets/common/src: ../../common/src/libworkrave-gtk2-private-1.0.so.1.0 ../../../../libs/utils/src/libworkrave-libs-utils.a -lmate-panel-applet-4 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangoft2-1.0 -lfontconfig -lfreetype -lgdk-x11-2.0 -lpangoft2-1.0 -lfontconfig -lfreetype -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 
/usr/bin/ld: CMakeFiles/mate-workrave-applet.dir/main-gtk2.c.o: in function `on_menu_about':
main-gtk2.c:(.text+0x489): undefined reference to `_'
collect2: error: ld returned 1 exit status
make[2]: *** [ui/applets/mate/src/CMakeFiles/mate-workrave-applet.dir/build.make:86: ui/applets/mate/src/workrave-applet] Error 1
make[2]: Leaving directory '/root/workrave/build'
make[1]: *** [CMakeFiles/Makefile2:1752: ui/applets/mate/src/CMakeFiles/mate-workrave-applet.dir/all] Error 2
make[1]: Leaving directory '/root/workrave/build'
```

**To Reproduce**

1.git clone  https://github.com/rcaelers/workrave.git
2. git checkout -b next origin/next
3. cd build
4. cmake -g ..
5 make

**Expected behavior**

Succeed to build

** Linux (please complete the following information in case you encountered the bug on Linux):**
 - Distribution: Debian
 - Distribution Version:  unstable
 - Desktop Environment: Gnome
 - Workrave Version next branch 

**Additional context**

There is no problem when UI is specified explicitly with cmake -g -DWITH_UI=Gtk+3.

**Comment by rcaelers** [comment]
The Qt5 port is not ready yet and currently focuses on macOS. Some gtk code will not properly compile with Qt5 enabled. This will be fixed at a later time when I continue with the Qt5 port.

I changed the default UI to Gtk+3 to prevent this compilation error.
