### ISSUE TITLE
Eliminate stale branches

### ISSUE THREAD

**Issue by xerus2000** [rcaelers/workrave#187]
![image](https://user-images.githubusercontent.com/13354331/80890817-2b857f00-8cc0-11ea-9654-a0204d098dd9.png)
There's quite a few stale branches, which make working with the repo unnecessarily noisy. Would be nice if these would be cleaned up :)

**Comment by rcaelers** [comment]
I removed master and gp-pages. But I don't want to remove the other. I will check if I can give the stale branches better, consistent names.

**Comment by xerus2000** [comment]
If the branches are there to preserve history, I would recommend to tag the latest commit of the branch and then remove it - that way you can still refer back to it but it doesn't interfere with active development.

**Comment by xerus2000** [comment]
Also, what's the point of master here?

**Comment by rcaelers** [comment]
I remove all stale branches and created new "archive/*" tags. The master branch has also been removed. I wasn't in use.
