### ISSUE TITLE
Add time as daily limit

### ISSUE THREAD

**Issue by xerus2000** [rcaelers/workrave#188]
I know I am using workrave for a slightly different intention, to remind myself to have regular breaks since this increases productivity, but of course also to guard against injuries. So this feature might not cater to the exact original use-case, but I'd like to have an additional fixed time as a daily limit since I love how this application reminds persistently but inobtrusively. 
I tried achieving the same thing with an alarm on the phone, but I clicked it away too quickly and I don't always have both phone and computer on me, which makes that not ideal.

**Comment by maciejs** [comment]
Isn't that duplicate of #93 ?

By the way, I dream of something a little different - the option of counting the daily limit as a fixed clock time, e.g. 8 hours (without stopping counting, e.g. when the computer is locked) from the time of first use computer on a given day, i.e. the time from which statistics start.

**Comment by xerus2000** [comment]
You're right, I'll close this then :)
