### ISSUE TITLE
Can't postpone while another break is overdue

### ISSUE THREAD

**Issue by xerus2000** [rcaelers/workrave#190]
**Describe the bug**
I wanted to postpone my Rest break while my Micro-break was overdue, but got some message similar to "Can't postpone while another break is overdue", which meant my only option was to skip the break.

**Expected behavior**
I can postpone my Rest break even when my Micro-break is overdue

**System**
OS: KDE neon User Edition 5.18 x86_64 based on Ubuntu bionic 18.04

**Comment by rcaelers** [comment]
Do you have the postpone button disabled for the microbreak? If this is the case, you can't postpone the restbreak until the microbreak timer has reset. The postpone button has a small progress bar on top that shows how long it takes for the postpone button to become available.

**Comment by xerus2000** [comment]
I have all postpone buttons enabled :)
Version is 1.10.41

**Comment by xerus2000** [comment]
Not an issue for me anymore, I'll reopen in case this troubles me again.
