### ISSUE TITLE
Getting an error after install  (libatkmm-1.6.so.1)

### ISSUE THREAD

**Issue by franciscomemoli** [rcaelers/workrave#193]
**Describe the bug**
After install workrave I tried to run it with no luck. I'm getting the next error:
workrave: error while loading shared libraries: libatkmm-1.6.so.1: cannot open shared object file: No such file or directory
after that I tried to install that lib and I get this:
command: sudo apt-get install libatkmm-1.6-1v5                                                                                                                                                        
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libatkmm-1.6-1v5 is already the newest version (2.24.2-3).
0 upgraded, 0 newly installed, 0 to remove and 191 not upgraded

**To Reproduce**
1. Install workrave with apt-get install workrave
2. run workrave

**Expected behavior**
To work 

**Linux:**
 - Distribution: [e.g. Ubuntu, Fedora, Debian, ...] 
elementary OS 5.1.2 Hera

 - Distribution Version: 
elementary OS 5.1.2 Hera
Built on Ubuntu 18.04.3 LTS

 - Desktop Environment: [e.g. Gnome, KDE, XFCE, MATE, Cinnamon, ...]
elementary os (GTK 3.22.30)
 - Workrave Version [e.g. 1.10]
1.10.43

**Comment by rcaelers** [comment]
Did you install Workrave from my PPA (https://launchpad.net/~rob-caelers/+archive/ubuntu/workrave)? I installed elementary and it seems to have an older version of Workrave.

Both the version from elementary and from my PPA run fine on my system. Though you get a double title bar (known issue: https://github.com/elementary/gala/issues/244)..

Workaround:

```
GTK_CSD=0 workrave
```

What is the output on your system of the following commands?
  
- `ldd /usr/bin/workrave` 
- `ls -la /usr/lib/x86_64-linux-gnu/libatkmm*`

**Comment by franciscomemoli** [comment]
Here you have the output for the commands

**ldd /usr/bin/workrave**
`
	linux-vdso.so.1 (0x00007fff113a0000)
	libXtst.so.6 => /usr/lib/x86_64-linux-gnu/libXtst.so.6 (0x00007f1d74fdf000)
	libXss.so.1 => /usr/lib/x86_64-linux-gnu/libXss.so.1 (0x00007f1d74ddb000)
	libgstreamer-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 (0x00007f1d74aa0000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f1d74768000)
	libgtkmm-3.0.so.1 => /usr/lib/x86_64-linux-gnu/libgtkmm-3.0.so.1 (0x00007f1d7401a000)
	libatkmm-1.6.so.1 => not found
	libgdkmm-3.0.so.1 => /usr/lib/x86_64-linux-gnu/libgdkmm-3.0.so.1 (0x00007f1d73dc9000)
	libgiomm-2.4.so.1 => not found
	libpangomm-1.4.so.1 => not found
	libglibmm-2.4.so.1 => not found
	libcairomm-1.0.so.1 => not found
	libsigc-2.0.so.0 => not found
	libdbusmenu-glib.so.4 => /usr/lib/x86_64-linux-gnu/libdbusmenu-glib.so.4 (0x00007f1d73bad000)
	libgtk-3.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-3.so.0 (0x00007f1d732a5000)
	libgdk-3.so.0 => /usr/lib/x86_64-linux-gnu/libgdk-3.so.0 (0x00007f1d72faf000)
	libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f1d72d62000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f1d72a45000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f1d72821000)
	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f1d72482000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f1d7222e000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f1d71f17000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1d71b8e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1d717f0000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1d715d8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1d713b9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1d70fc8000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f1d70db6000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f1d70bb2000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1d709aa000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1d707a6000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f1d7057e000)
	libatkmm-1.6.so.1 => not found
	libgiomm-2.4.so.1 => not found
	libpangomm-1.4.so.1 => not found
	libglibmm-2.4.so.1 => not found
	libcairomm-1.0.so.1 => not found
	libsigc-2.0.so.0 => not found
	libgiomm-2.4.so.1 => not found
	libglibmm-2.4.so.1 => not found
	libcairomm-1.0.so.1 => not found
	libsigc-2.0.so.0 => not found
	libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007f1d70371000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f1d70161000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f1d6ff5b000)
	libcairo-gobject.so.2 => /usr/lib/x86_64-linux-gnu/libcairo-gobject.so.2 (0x00007f1d6fd52000)
	libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007f1d6fb2c000)
	libatk-bridge-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 (0x00007f1d6f8fb000)
	libepoxy.so.0 => /usr/lib/x86_64-linux-gnu/libepoxy.so.0 (0x00007f1d6f5fa000)
	libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007f1d6f3e4000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f1d6f19f000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f1d6ef9c000)
	libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f1d6ed91000)
	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f1d6eb87000)
	libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007f1d6e984000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f1d6e781000)
	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f1d6e542000)
	libwayland-cursor.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007f1d6e33a000)
	libwayland-egl.so.1 => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007f1d6e138000)
	libwayland-client.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007f1d6df29000)
	libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007f1d6dd20000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f1d6da7b000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f1d6d7c7000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f1d6d595000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f1d6d392000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f1d6d185000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f1d6cf7b000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1d6cd5e000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f1d6cb36000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f1d6c91b000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007f1d6c6c7000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f1d6c4bf000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f1d6c24d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1d755d6000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f1d6c049000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f1d6be43000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f1d6bbf6000)
	libatspi.so.0 => /usr/lib/x86_64-linux-gnu/libatspi.so.0 (0x00007f1d6b9c6000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f1d6b728000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f1d6b4f6000)
	libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f1d6b2ef000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f1d6b0a2000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f1d6ae8d000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f1d6ac09000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f1d6a9dc000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f1d6a7d5000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f1d6a5af000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f1d6a393000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f1d6a077000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f1d69e62000)
`
**ls -la /usr/lib/x86_64-linux-gnu/libatkmm***
`zsh: no matches found: /usr/lib/x86_64-linux-gnu/libatkmm*
`

As I understand I don't have any libatkmm install but when I want to install using sudo apt-get install libatkmm-1.6-1v5 I get the error that I mention on the last comment, which is weird...

I tryied this too 
GTK_CSD=0 workrave
but I got the same error
workrave: error while loading shared libraries: libatkmm-1.6.so.1: cannot open shared object file: No such file or directory

I installed the workrave with this commands
sudo add-apt-repository ppa:rob-caelers/workrave  
sudo apt-get update
sudo apt-get install workrave
is that right?

**Comment by rcaelers** [comment]
Strange, the atkmm package is installed, but the content is not there. 

So what is the output of:

- `dpkg -l | grep  libatkmm-1.6-1v5`
- `dpkg -L libatkmm-1.6-1v5 | grep so`

Maybe `apt-get install --reinstall libatkmm-1.6-1v5` solves the problem..

**Comment by franciscomemoli** [comment]
Woow! working!
ok, I had to run the reinstall command for that lib and some more: here you have all the libs on which I had problems:

apt-get install --reinstall libatkmm-1.6-1v5 
apt-get install --reinstall libglibmm-2.4-1v5
apt-get install --reinstall libpangomm-1.4-1v5
apt-get install --reinstall libcairomm-1.0-1v5
apt-get install --reinstall libsigc++-2.0-0v5

Just if this is useful for some one here you have the output of the dpkg commands:

**dpkg -l | grep libatkmm-1.6-1v5** 
ii  libatkmm-1.6-1v5:amd64                            2.24.2-3                                        amd64        C++ 
wrappers for ATK accessibility toolkit (shared libraries)

 **dpkg -L libatkmm-1.6-1v5 | grep so**
/usr/lib/x86_64-linux-gnu/libatkmm-1.6.so.1.1.0
/usr/lib/x86_64-linux-gnu/libatkmm-1.6.so.1
