### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by Altm** [rcaelers/workrave#197]
I try open settings, then an error message appears exception %ws%ws%ws

My OS Windows 10 Pro
The error is reproduced on versions 1.10.44 and 1.10.43

![err](https://user-images.githubusercontent.com/6719268/82036601-c3646f00-96a9-11ea-95a4-ae3465169ac9.png)

**Comment by Felan578** [comment]
Same problem on Windows 8.1

**Comment by rcaelers** [comment]
Indeed. I also managed to reproduce this. It will be fixed in 1.10.45.
