### ISSUE TITLE
Segmentation fault (core dumped) on first run

### ISSUE THREAD

**Issue by DaveDixon** [rcaelers/workrave#203]
Ubuntu 18.04 LTS

Installed from  http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 workrave amd64 1.10.16-2ubuntu1

Fails from launcher. From command line, fails with Segmentation fault (core dumped).

**Comment by rcaelers** [comment]
I have installed Ubuntu 18.04 LTS in a virtual machine and Workrave 1.10.16 runs fine here.

Did you try to reinstall Worrave (apt-get install --reinstall workrave)?
Does ubuntu give a crashdump?
Are you using a language different from English?
