### ISSUE TITLE
Dark Interface for breaks on Windows

### ISSUE THREAD

**Issue by Nirose** [rcaelers/workrave#214]
Not of any priority but would it be possible to get a darker theme for the micro-breaks and rest breaks in Windows? It would be much more comfortable for the eyes when working evenings and nights.

**Comment by iemiil** [comment]
it would really be an improvement for night crawlers... 
when in dark mode, the micro-break pop up is a frequent punch in the eyes :-/
thank you!

**Comment by Nickromancer** [comment]
Dark mode is a must have for folks like me who have issues with low contrast, as dark modes are the only way to have high contrast without major eyestrain.. the current colors on the entire program give me a bit of a migraine after awhile so I keep having to turn it off and on throughout the day.

**Comment by rcaelers** [comment]
This has been implemented in Workrave 1.11.
