### ISSUE TITLE
Reset Settings to default settings

### ISSUE THREAD

**Issue by p2635** [rcaelers/workrave#220]
**Describe the feature**
I set my own timer settings but realised I don't want them anymore, I want to go back to the default settings but I don't know what they are.

**Screenshots**
Possibly have a button here which says 'Reset settings' with a confirmation 'This will reset all settings, are you sure?'.
![image](https://user-images.githubusercontent.com/4522927/89900968-5004c780-dbdc-11ea-83fc-d414e8bbc883.png)

**Comment by p2635** [comment]
Is there a workaround for this? Maybe I can delete the settings file or something and let it regenerate but I don't know where it is located.

**Comment by rcaelers** [comment]
On Windows, you can start regedit and delete 'CURRENT_USER/Software/Workrave'.

**Comment by lestephane** [comment]
On linux, my workaround to reset the settings to defaults was to use  `dconf-editor` and select `Reset recursively` for the `org.workrave` config namespace. It took a few tries to really reset everything, so a button for that purpose will indeed be welcome.

![image](https://user-images.githubusercontent.com/5460884/206894828-33cb567f-32d6-4f56-80d3-a981aa8ab746.png)

**Comment by davidhedlund** [comment]
> On linux, my workaround to reset the settings to defaults was to use `dconf-editor` and select `Reset recursively` for the `org.workrave` config namespace. It took a few tries to really reset everything, so a button for that purpose will indeed be welcome.
> 
> ![image](https://user-images.githubusercontent.com/5460884/206894828-33cb567f-32d6-4f56-80d3-a981aa8ab746.png)

* Works: dconf reset -f /org/mate/caja/
* Works: gsettings reset-recursively org.mate.caja
* Works: dconf reset -f /org/workrave/
* Does not work: gsettings reset-recursively org.workrave

Do you have idea how to reset workrave recursively with gsettings @rcaelers (thank you for your contributions) ?

**Comment by davidhedlund** [comment]
> > On linux, my workaround to reset the settings to defaults was to use `dconf-editor` and select `Reset recursively` for the `org.workrave` config namespace. It took a few tries to really reset everything, so a button for that purpose will indeed be welcome.
> > ![image](https://user-images.githubusercontent.com/5460884/206894828-33cb567f-32d6-4f56-80d3-a981aa8ab746.png)
> 
>     * Works: dconf reset -f /org/mate/caja/
> 
>     * Works: gsettings reset-recursively org.mate.caja
> 
>     * Works: dconf reset -f /org/workrave/
> 
>     * Does not work: gsettings reset-recursively org.workrave
> 
> 
> Do you have idea how to reset workrave recursively with gsettings @rcaelers (thank you for your contributions) ?

@rcaelers Can you please help me with this? This is one of very few issues in GNU/Linux that blocks me from running everything from scripts.
