### ISSUE TITLE
Gnome system tray applet menu not complete

### ISSUE THREAD

**Issue by Schparky** [rcaelers/workrave#233]
**Describe the bug**
The Gnome system tray applet menu has only one item: "Open Workrave", which usually does nothing. On occasion it opens a dialog that says Workrave is already running.

**To Reproduce**
1. Install Workrave and the Gnome system tray applet
2. Suspend the computer
3. Wake the computer
4. Click the system tray applet

**Expected behavior**
The full Workrave system tray applet menu should be accessible

**Screenshots**
![image](https://user-images.githubusercontent.com/3172830/93944175-5c0e9980-fcf1-11ea-94b8-a881088d7755.png)
![image](https://user-images.githubusercontent.com/3172830/93944249-88c2b100-fcf1-11ea-8128-336fcf39e20e.png)

**Linux (please complete the following information in case you encountered the bug on Linux):**
 - Distribution: Ubuntu
 - Distribution Version: 20.04.1 LTS
 - Desktop Environment: Gnome 3.36.3
 - Workrave Version [e.g. 1.10]

**Additional context**
- Windowing System: X11
- Workrave installed from Ubuntu Software app

To recover, kill the workrave process and restart it.

**Comment by rcaelers** [comment]
I assume you are using the Workrave 1.10.37 that comes with Ubuntu 20.04? The issue you describe should be fixed in version 1.10.41: 

\* Workrave 1.10.41
** Fix incomplete Gnome Shell applet menu with latest version of Gnome Shell

You could try to install the latest Workrave from my PPA (see https://workrave.org/download/ubuntu/)

**Comment by Schparky** [comment]
Thank you for the suggestion. I did install from the PPA, and I believe it replaced the Ubuntu version. I can't see the version number anywhere. The timestamp on /usr/bin/workrave is May  9 08:41 which seems to coincide with 1.10.44. It doesn't seem to change the behavior I described above, however.

**Comment by Schparky** [comment]
Updating to say the problem is no longer present on my machine. I recently rebooted to troubleshoot an unrelated issue, so that may have contributed to the solution. I also noticed that the applet menu now contains an "About..." item. Wondering if that is a relatively new addition.

**Comment by rcaelers** [comment]
After installing 1.10.44 you have to reload the extension, e.g. by logging out/in or restarting. So that could be the reason. Not sure if "About" is new. Not as far as I know....

I will close this issue. Please reopen if you still encounter incomplete menus.
