### ISSUE TITLE
there's a little mistake in the italian translation

### ISSUE THREAD

**Issue by iemiil** [rcaelers/workrave#234]
Hi,
first of all, I love your piece of software, thanks!

there's a little mistake in the italian translation: 
in the statistics, it should be: "effettuate" instead of "efettuate". in other words there's an f missing.

![image](https://user-images.githubusercontent.com/71920734/94335647-41803d00-ffdd-11ea-97b2-8429ff1afea5.png)

![image](https://user-images.githubusercontent.com/71920734/94335693-8c9a5000-ffdd-11ea-8684-e3e0ab49c70b.png)

**Comment by rcaelers** [comment]
Thanks! I fixed the typo.

**Comment by iemiil** [comment]
Great! Dank je!
