### ISSUE TITLE
How to backup workrave settings?

### ISSUE THREAD

**Issue by snowman** [rcaelers/workrave#235]
I am using `arch linux`, but could not found the config file path.

**Comment by rcaelers** [comment]
On Linux, you can use `dconf dump /org/workrave/ > file` to save the settings.

Also, Workrave stores your statistics and current state in ~/.workrave. So you may also want to back up that directory.

**Comment by snowman** [comment]
Thanks for your help :) :+1: 

That's why this not work:
1. Open workrave to input username such as `bitcoin`
2. $ fd -0 -tf -IHp workrave / | xargs -0 grep -e bitcoin -l
