### ISSUE TITLE
Wayland - options missing

### ISSUE THREAD

**Issue by ilippert** [rcaelers/workrave#236]
**Describe the bug & Linux context**

I run Fedora 5.8.12-200.fc32.x86_64 Gnome

and have updated to 1.10.44 and use workrave under wayland (well returning to workrave after some years).

using https://koji.fedoraproject.org/koji/buildinfo?buildID=1618818

The problem is, I only see the workrave window; the only interaction I can get is to click on the cup. I cannot access options anywhere. 

 

**Expected behavior**
I see at https://github.com/rcaelers/workrave/issues/233 that an "Gnome system tray applet menu" should be available, but cannot find it.

![Screenshot from 2020-10-02 19-02-28](https://user-images.githubusercontent.com/20518297/94949841-e620e400-04e1-11eb-927f-dc16c132da6f.png)

**Comment by rcaelers** [comment]
I installed fedora 32 and the Workrave from the repository you mentioned. When I right-click in the main window, I get a popup menu. Also running wayland. Right click does not work for you?

<img width="250" alt="popup menu" src="https://user-images.githubusercontent.com/80881/94993722-4328a280-0593-11eb-9a6c-76be0dd28d21.png">

You can enable a gnome applet/extension. See: https://workrave.org/docs/applets/gnome/

**Comment by ilippert** [comment]
so many thanks! both work - sorry for my ignorance earlier!

**Comment by ilippert** [comment]
Ok, I am re-opening it, to seek support in identifying the underlying problem.

I face this situation:
the pop-up menu does not show when I power on my fourth displayport driven monitor. If I only use hdmi-monitors, then the menu shows. 

I suspect this might relate to an underlying issue with a library workrave is using. I suspect so, because I sense a slightly related problem in https://github.com/texstudio-org/texstudio/issues/1300

**Comment by ilippert** [comment]
problem solved.
