### ISSUE TITLE
Feature request: timeout for Reading and Quiet modes

### ISSUE THREAD

**Issue by pawelszramowski** [rcaelers/workrave#240]
It should be possible to configure a maximum time after which Workrave is going to automatically switch from Reading or Quiet mode back to Normal mode (or at least remind the user to do it) because it is VERY easy to forget about doing it manually, e.g. after a meeting ends. The whole point of using this application is then lost.
It would probably be best to specify the timeout (or lack thereof) when switching modes because a value configurable within Settings may not be suitable for every situation (e.g. short meeting vs. long meeting).

I managed to automate it by having Task Scheduler periodically execute [send_workrave_command.c](contrib/send_menu_command/win32/send_workrave_command.c) with `MENU_COMMAND_MODE_NORMAL` argument, however, it is a solution for power users and it is cumbersome because the scheduler is not synchronized to Workrave.

**Comment by rcaelers** [comment]
See also #98, which only mentions 'suspend'.

**Comment by rcaelers** [comment]
Duplicate of #98.

(cleaning up duplicate issue. #98 also mentions quiet mode it seems)

**Comment by Chealer** [comment]
@rcaelers: #98 is about the suspended mode. This one is about the reading mode (notably). Although Wokrave 1.11 RC 3 solved #98, as far as I can see, there is still no way to switch to reading mode only temporarily.

Are you confident that this duplicates #98?
