### ISSUE TITLE
debian/gnome workrave window disappears and never comes back

### ISSUE THREAD

**Issue by rafmeeusen** [rcaelers/workrave#244]
Suddenly my workrave GUI window disappeared.
Using Debian 10/Gnome. 
Cannot get it back, even not after full re-install apt purge / apt install. 

Not sure how to reproduce. Suddenly happened while moving some windows around. 

I guess I would need to clean dconf configuration stuff before full re-install in order to fix? 
Didn't try this yet. 
Before I do that, anything I should keep/log to find out what root cause is? 

system:
Debian GNU/Linux 10 \n \l
Linux holmes 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux
Gnome 3.30.2
Workrave Version: 1.10.23-5

**Comment by rafmeeusen** [comment]
think I found the dconf data: 

$ dconf dump /org/workrave/
[general]
operation-mode=0

[timers/daily-limit]
snooze=1200
activity-sensitive=true
limit=21600

[timers/micro-pause]
auto-reset=30
snooze=150
activity-sensitive=true
limit=600

[timers/rest-break]
auto-reset=600
snooze=180
activity-sensitive=true
limit=2700

[distribution]
port=27273
reconnect-attempts=3
reconnect-interval=15

[gui/main-window]
cycle-time=10
head=0
x=55
enabled=false
y=64

[gui]
trayicon-enabled=true

[gui/applet]
cycle-time=10

[gui/breaks/daily-limit]
skippable-break=true
ignorable-break=true

[gui/breaks/micro-pause]
skippable-break=true
ignorable-break=true

[gui/breaks/rest-break]
enable-shutdown=true
ignorable-break=true
skippable-break=true

[breaks/daily-limit]
enabled=true

[breaks/micro-pause]
max-preludes=0
enabled=true

[breaks/rest-break]
enabled=true

[sound]
volume=100

[sound/events]
micro-break-started='/usr/share/sounds/workrave/default/micro-break-started.wav'
exercises-ended='/usr/share/sounds/workrave/default/exercises-ended.wav'
break-prelude='/usr/share/sounds/workrave/default/break-prelude.wav'
rest-break-started='/usr/share/sounds/workrave/default/rest-break-started.wav'
daily-limit='/usr/share/sounds/workrave/default/daily-limit.wav'
micro-break-ended='/usr/share/sounds/workrave/default/micro-break-ended.wav'
exercise-step='/usr/share/sounds/workrave/default/exercise-step.wav'
rest-break-ended='/usr/share/sounds/workrave/default/rest-break-ended.wav'
exercise-ended='/usr/share/sounds/workrave/default/exercise-ended.wav'
break-ignored='/usr/share/sounds/workrave/default/break-ignored.wav'

**Comment by rafmeeusen** [comment]
OK, could fix the issue by clearing my dconf.

Here's what I did to fix + the fresh dconf: 

$ dconf reset -f /org/workrave/

< started workrave again; got back gui >

$ dconf dump /org/workrave/
[gui/main-window]
head=0
x=-771
y=104

[sound/events]
micro-break-started='/usr/share/sounds/workrave/default/micro-break-started.wav'
exercises-ended='/usr/share/sounds/workrave/default/exercises-ended.wav'
break-prelude='/usr/share/sounds/workrave/default/break-prelude.wav'
rest-break-started='/usr/share/sounds/workrave/default/rest-break-started.wav'
daily-limit='/usr/share/sounds/workrave/default/daily-limit.wav'
micro-break-ended='/usr/share/sounds/workrave/default/micro-break-ended.wav'
exercise-step='/usr/share/sounds/workrave/default/exercise-step.wav'
rest-break-ended='/usr/share/sounds/workrave/default/rest-break-ended.wav'
exercise-ended='/usr/share/sounds/workrave/default/exercise-ended.wav'
break-ignored='/usr/share/sounds/workrave/default/break-ignored.wav'

**Comment by rafmeeusen** [comment]
Meanwhile could also reproduce the issue: 

it seems that I must have done following to trigger the issue: 
1) switching to activities overview, i.e. seeing all windows ordered (https://help.gnome.org/misc/release-notes/3.6/users-activities-overview.html.en)
2) clicking the X to close the application

After that: 
$ dconf dump /org/workrave/
[gui/main-window]
head=0
x=-665
enabled=false
y=116

(and workrave runs in background, process not stopped)
(and restarting/reinstalling doesn't change this) 

To fix: 
$ dconf write /org/workrave/gui/main-window/enabled true

Tried with another application (firefox). Here the X does end all firefox processes related to that window.
So guess this is a bug somewhere ?

**Comment by rcaelers** [comment]
When you close the Workrave main window, Workrave should quit if there is no other way to re-open the window, e.g. using the menu of the status icon or applet. This mechanism failed, so the main window was closed without any way to re-open. This will be fixed in 1.10.45 (see also #259)
