### ISSUE TITLE
On high resolutions screen the windows applet is very small: The (Windows 10) scaling of 200% is not taken into account

### ISSUE THREAD

**Issue by J-u-n-o** [rcaelers/workrave#246]
On my Windows10 laptop 2880x1920, I have a scaling of 200%. 
- This causes the widget in the window taskbar to be too small
- The mouse hoover on the workrave.org link too small
- The windows 10 notification also being too small, but maybe this last is solved by a reboot.

**Comment by rcaelers** [comment]
Workrave still uses the GTK2 user-interface library on Windows. One of the next versions should switch to GTK3. I expect that this will fix the scaling issue. GTK2 does not support high-dpi.

**Comment by rcaelers** [comment]
If have fixed the size of the icons in the Windows taskbar applet. As far as I can see everything else has the correct size.

I compared Workrave with and without scaling (or more precisely, either my virtualization software performs the scaling and Windows uses 100%, or my virtualization software does not scale and Windows performs 200% scaling). Both look identical.

Where did you find the mouse hoover on the workrave.org link ? The link in the about windows doesn't have a mouse hover as far as I can see. I don't know of any other "workrave.org" link.

**Comment by rcaelers** [comment]
Workrave seems to look fine in my HiDPI Windows virtual machine with 200% scaling. If you still see scaling issues in Workrave 1.10.45 or later, please reopen this issue and add a screenshot. Thanks.
