### ISSUE TITLE
Bug: Workrave counts watching videos as activity (Ubuntu 20.04/Gnome)

### ISSUE THREAD

**Issue by anja-goldschmidt** [rcaelers/workrave#248]
**Describe the bug**
When a video is streaming in Youtube, Workrave counts this as activity and keeps counting down to the next break even when I keep my hands of mouse and keyboard. The same happens when I use the Discord app to make a video call.

**To Reproduce**
1. Start Workrave
2. Open Youtube in your browser and start streaming a video (or start a video call via the Discord app).
3. Switch to the small Workrave status window, keep your hands off mouse and keyboard and observe that it keeps counting down to the next break.

**Expected behavior**
As neither mouse nor keyboard are being used, video calling or streaming should not count as activity.

**Screenshots**
na

** Linux (please complete the following information in case you encountered the bug on Linux):**
 - Distribution: Ubuntu 
 - Distribution Version: 20.04
 - Desktop Environment: Gnome
 - Workrave Version 1.10.44

** Windows (please complete the following information in case you encountered the bug on Windows):
 - na

**Additional context**
If this is the intended behaviour (e.g. because when streaming a video it is assumed I look at the screen and hence my eyes are active), it would be nice to have an option to switch this off. In hour-long video calls with colleagues it gets rather tiring to have to click away a small break every five minutes.

**Comment by rcaelers** [comment]
This is not the intended behavior. Workrave should stop the timers when you are not using keyboard and mouse, even when watching videos. Workrave 1.10.44 fixes a similar issue (#181). I couldn't reproduce this on my system, so perhaps your environment is different.

Could you execute the following in a terminal and share the output?
`echo $XDG_SESSION_DESKTOP $XDG_SESSION_TYPE`

**Comment by anja-goldschmidt** [comment]
Hi, thanks for the quick reaction. #181 does sound like the bug I observed. Maybe I accidentally downloaded and installed an older version of workrave (installation was 10 days ago). How could I easily check my version?

The output of the echo-command is as follows: ubuntu x11

**Comment by rcaelers** [comment]
The easiest way to check the version is to right-click in the main timer window and select 'about' (https://workrave.org/docs/menus/).

I will check the 'Ununtu on X11' later tody.

**Comment by anja-goldschmidt** [comment]
Ok, it does look like I have an older version: 1.10.37. My appologies for the wrong info in the bug description. When trying to update with 'sudo apt-get install workrave' I get the information that I have the newest version (1.10.37). I'm still reasonably new to Linux, is there something I am doing wrong? How can I get 1.10.44?

**Comment by kees-jan** [comment]
1.10.37 is the newest Workrave version _shipped by ubuntu_. For beginners, it is generally best to stick to software shipped by Ubuntu. They make some effort to test that all components work together, and contain no viruses/malware.

We supply the latest Workrave version for Ubuntu in what is called a "Personal Package Archive". You can choose to [add it to your system](https://launchpad.net/~rob-caelers/+archive/ubuntu/workrave) and receive the latest (stable) version, as soon as it is released. That would amount to opening a terminal and typing
```
sudo add-apt-repository ppa:rob-caelers/workrave
sudo apt update
sudo apt full-upgrade
```
That last command updates all installed packages, not just Workrave, so if you haven't installed any updates recently, that might be a bit of work.

**Comment by anja-goldschmidt** [comment]
Ok, thank you! Then I know how to proceed and will close this issue.
