### ISSUE TITLE
Gnome 3.38.1: Usage of object.actor is deprecated for WorkraveButton

### ISSUE THREAD

**Issue by rfc2822** [rcaelers/workrave#251]
When using Workrave 1.10.44 and Gnome 3.38.1 (both default versions in Manjaro Linux 20.2), gnome-shell randomly freezes with:

```
workrave-applet: start @ 133209002
Usage of object.actor is deprecated for WorkraveButton
 get@resource:///org/gnome/shell/ui/environment.js:314:29
 _init@/usr/share/gnome-shell/extensions/workrave@workrave.org/extension.js:176:9
 wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
 enable@/usr/share/gnome-shell/extensions/workrave@workrave.org/extension.js:486:27
 _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
 loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:348:26
 _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:586:18
 collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
 _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:565:19
 _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:595:18
 _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:626:18
 init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
 _initializeUI@resource:///org/gnome/shell/ui/main.js:269:22
 start@resource:///org/gnome/shell/ui/main.js:159:5
 @<main>:1:47
```

It looks like there is some `object.actor` that shouldn't be used anymore, but I'm not sure whether this should be addressed by Workrave or solely by gnome-shell.

See https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3413 for more information.

(And thanks for this wonderful project that reminds me of taking screen breaks!)

**Comment by rcaelers** [comment]
I fixed the deprecation warning. I doubt this has anything to do with the random freezes. The deprecation warning is logged when the Workrave applet starts. Do you see any suspicious logging (e.g. from journalctl) when the freeze occurs>

**Comment by rcaelers** [comment]
I am closing this issue. Please reopen if you still encounter freezes when using the Gnome Shell applet.
