### ISSUE TITLE
Workrave applet doesn't sustain its length in taskbar in Windows

### ISSUE THREAD

**Issue by OkazakiNagisa** [rcaelers/workrave#252]
**Describe the bug**
Workrave applet remains a fixed position in taskbar, ignoring tray changes. And it have not a minimal length. This two bugs make the applet not very useful because users have to constantly adjust its positions to make it visible.

**To Reproduce**
1. Just enable the applet.

** Windows (please complete the following information in case you encountered the bug on Windows):
 - Windows Version: Windows 10
 - Workrave Version 1.10.44

**Comment by kees-jan** [comment]
I've seen the same behavior. I've worked around it by placing the applet on the left of the taskbar, between the Start button and the proper taskbar, instead of on the right, between the task bar and the system tray.

Since neither the start button nor the task bar change size, the current applet behavior is less of a problem there.

**Comment by OkazakiNagisa** [comment]
That's a good idea! But personally, I prefer to place it on the left side of system tray. It's better to make the applet be able to automatically adjust its position still. It seems Deskband api support this feature (e.g. ctfmon.exe before Windows 10, Thinkpad Power Manager).

**Comment by kees-jan** [comment]
Well, yes, of course it is better to actually fix the problem. I'm not proposing to close this issue. Fixing it, however, is unfortunately outside of my area of expertise, so I'm hoping Rob will chime in :wink:

**Comment by rcaelers** [comment]
So let's chime in :smiley: Workrave should now calculate the minimum and preferred size of the Windows applet.

A development build is available for testing: https://snapshots.workrave.org/snapshots/v1.10/20201127-v1_10_44-91-g4252ce86da/workrave-win32-v1_10_44-91-g4252ce86da-20201127.exe

**Comment by OkazakiNagisa** [comment]
Awesome🎉

**Comment by kees-jan** [comment]
Damn... And now I have to wait until after Corona before I'll be able to test this :-(
