### ISSUE TITLE
Workrave Cinnamon Applet Flickers a bit

### ISSUE THREAD

**Issue by mgscreativa** [rcaelers/workrave#253]
**Describe the bug**
The applet timer bumps a little bit in Linux Mint 20 - Cinnamon

**To Reproduce**
1. install Workrave from PPA
2. Enable Cinnamon applet with timer
3. See it bump up and down a little

**Expected behaviour**
No applet bump as the other icons

**Screenshots**
You can check that the timer got up by one pixel, and that's happens all the time
![1](https://user-images.githubusercontent.com/1286632/100455459-7ec88000-309d-11eb-9e1f-81887ed9ce3d.png)
![2](https://user-images.githubusercontent.com/1286632/100455461-7ff9ad00-309d-11eb-933a-a764ba1eb1ac.png)

**Linux:**
 - Distribution: Linux Mint
 - Distribution Version: 20
 - Desktop Environment: Cinnamon
 - Workrave Version: 1.10.44

**Comment by rcaelers** [comment]
This issue should be fixed now.

Whether the applet bumps up and down seems to depend on the panel height.  If you make the panel height 1 pixel larger or smaller it will probably stop bumping. So until 1.10.45 is released, you can try that as a workaround.

**Comment by mgscreativa** [comment]
You're right, setting panel height to 33 worked
