### ISSUE TITLE
Crash after changing wav for event

### ISSUE THREAD

**Issue by MCHuijgen** [rcaelers/workrave#256]
When changing the wav file for an event, Workrave crashes. 

1. Go to Preferences > User interface > Sounds
2. Click on an event in the list (e.g. Break prompt)
3. Click on the button below with the respective wav file
4. Select another wav file in the list and click Open
5. Click Close to close Preferences.
6. Again, go to Preferences > User interface > Sounds
7. Click on an event in the list (e.g. Break prompt)
8. Click on the button below with the respective wav file
9. Select another wav file in the list and click Open
10. A crash notification displays

The crash log:
[workrave-crashlog.txt](https://github.com/rcaelers/workrave/files/5621872/workrave-crashlog.txt)

**Expected behavior**
The crash does not occur.

** Windows:
 - Windows Version: Windows 10 1803 and 1909
 - Workrave Version 1.10

**Additional context**
Apparently, the change of the wav file is saved in registry, since restarting Workrave and going to  Preferences > User interface > Sounds the changed wav file of step 9 is visible there.
The crash did not always occur when Workrave is quitted completely between step 5 and 6.

**Comment by rcaelers** [comment]
I managed to reproduce this with Workrave 1.10.1, but not with 1.10.44. Could you check if upgrading to 1.10.44 fixes the problem for you?

**Comment by MCHuijgen** [comment]
Yes, thanks! We're using 1.10.1 (although the About says 1.10), that I got from either Sourceforge or workrave.org before your update from May last year. I downloaded 1.10.44 and I don't see that issue anymore. Thanks for looking into this!
