### ISSUE TITLE
'About' in menu is not translated

### ISSUE THREAD

**Issue by MCHuijgen** [rcaelers/workrave#257]
About in the menu does not translate, although it is translated in the po/mo.

I edited the Dutch language file (some spelling errors), but I noticed that 'About' is not translated, although it is there in de po/mo file.

**Screenshots**
![image](https://user-images.githubusercontent.com/49674916/100739211-07fdf080-33d7-11eb-9d35-b61a4509b004.png)
MO file: [workrave.zip](https://github.com/rcaelers/workrave/files/5622513/workrave.zip)

** Windows:**
 - Windows Version: Windows 10
 - Workrave Version 1.10

**Comment by rcaelers** [comment]
The translation seems to be fine in Workrave 1.10.44. I just tested 1.10.1 (the oldest version on Github). This version also has the missing Dutch 'About' translation.

Are use using 1.10? or a more recent version?

**Comment by MCHuijgen** [comment]
I'm using 1.10. And you're right, in 1.10.44 it is OK. Which brings me to another translation issue.

In workrave.mo I adjusted some Dutch translations (mostly minor spelling issues), but some changes in the translations in the exercises are not visible (like I changed 'houdt' to 'hou' in the screenshot below) 
MO file: [workrave.zip](https://github.com/rcaelers/workrave/files/5776586/workrave.zip)

![image](https://user-images.githubusercontent.com/49674916/103785692-cf87ad00-503b-11eb-8ed5-d24642b4a1fc.png)

All other changes I made in the MO file in other parts of the GUI can be observed, but not in the exercises. I tried to find other files which could hold these translations, but I couldn't find them. Do you have any ideas what might be causing this?

**Comment by rcaelers** [comment]
Translations for the exercises are handled differently compared to the other translated text. Build-time, the translations are merged into [exercises.xml](https://github.com/rcaelers/workrave/blob/branch_v1_10/frontend/plugin/exercises/common/share/exercises.xml.in). The result of this merge looks like:

 ```
<exercise>
    <title>Turn your head</title>
    <title xml:lang="bg">Завъртете глава</title>
     ...
    <title xml:lang="nb">Snu hodet</title>
    <title xml:lang="nl">Draai je hoofd</title>
    <title xml:lang="pl">Obroty głowy</title>
     ...
    <description xml:lang="nl">Draai je hoofd naar links en houdt dat 2 seconden vast. Draai daarna je hoofd naar rechts en houdt dat 2 seconden vast.</description>
     ...
```

You can find the merged XML file in the directory where you installed Workrave: `share\exercises\exercises.xml`

**Comment by MCHuijgen** [comment]
Thanks Rob! You can close this issue.

Besides this: I have some suggestions/improvements for the Dutch translation, which I would like to discuss with you. Can we have contact about this?
