### ISSUE TITLE
Loses GUI elements after start

### ISSUE THREAD

**Issue by cclamb** [rcaelers/workrave#259]
**Describe the bug**
After starting workrave, it will disappear from the dock (I use dash-to-dock) and if I had the window open, it will disappear as well. The program is still running however, as when i try to restart I get the "is workrave running?" dialog.

**To Reproduce**
1. Start workrave (command line is fine)
2. Wait for a minute or so, workrave's UI will disappear and it won't be in the dock.
3. Try to restart, see the "is it running" dialog.

**Expected behavior**
To continue to be attached to the GUI and controllable.

** Linux (please complete the following information in case you encountered the bug on Linux):**
 - Distribution: Ubuntu
 - Distribution Version: 20.04 LTS
 - Desktop Environment: Ubuntu/Gnome, with dash-to-dock
 - Workrave Version 1.10

**Comment by alisaaalehi** [comment]
Same here, with Ubuntu 16.04 LTS

**Comment by rcaelers** [comment]
I managed to reproduce this issue, and I am working on a fix. As a workaround, you can enable the Gnome Shell applet (see https://workrave.org/docs/applets/gnome/).
