### ISSUE TITLE
[bug] CPU usage raise to 100%

### ISSUE THREAD

**Issue by mattia-b89** [rcaelers/workrave#260]
**Describe the bug**
After ~30 minutes of daily usage, Workrave CPU utilization raise to 100%

**To Reproduce**
1. login in GNOME (Xorg)
2. Use it for 30 minutes
3. Check CPU usage

**System**
 - Distribution: Arch Linux
 - Distribution Version: rolling release
 - Desktop Environment: GNOME
 - Workrave Version 1.10.44-2

**Comment by rcaelers** [comment]
I have installed Arch Linux and Workrave that come with Arch. So far I haven't been able to reproduce this problem.

Does the CPU load depend on other software that is running (e.g. video audio playback)? Did you change any settings? (in particular, did you enable networking?).

Could you run `sudo gdb -batch -ex bt -p <workrave-process-id>` a couple of times to get a stack trace of Workrave?

**Comment by mattia-b89** [comment]
When I have to run `gdb`? when workrave works normally or during a 100% CPU spike?

PS: I use Firefox to surf the web when issue happens; for safety I cleared ~/.workrave directory

**Comment by rcaelers** [comment]
Please run gdb when Workrave uses 100% CPU.

**Comment by mattia-b89** [comment]
It's now three days I have been using Workrave after I reset .config folder and I haven't yet encountered the issue, so we can close it as "not-a-bug"
