### ISSUE TITLE
Workrave gone from gentoo packages

### ISSUE THREAD

**Issue by blabno** [rcaelers/workrave#261]
**Describe the bug**
I've just updated my Gentoo Linux and am unable to install workrave using the commands described in https://workrave.org/download/.

**To Reproduce**
```bash
emerge --sync
sudo emerge --ask --verbose workrave
```

>These are the packages that would be merged, in order:
>
>Calculating dependencies... done!
>
>emerge: there are no ebuilds to satisfy "workrave".

**Expected behavior**
Package should be found and installed.

** Linux (please complete the following information in case you encountered the bug on Linux):**
 - Distribution: Gentoo
 - Distribution Version:  
 - Desktop Environment: Fluxbox

**Comment by rcaelers** [comment]
It seems Workrave was removed from Gentoo. See https://bugs.gentoo.org/708006. I couldn't find any other Gentoo repository that has Workrave, so I removed Gentoo from the website. I have no experience with Gentoo, so I can't provide you with a Gentoo package. You could download the source and build Workrave from source.
