### ISSUE TITLE
Tray icon does not appear on Ubuntu 18.04

### ISSUE THREAD

**Issue by cifkao** [rcaelers/workrave#265]
**Describe the bug**
There is no icon in the system tray on my machine, even though the option is checked in the settings.

Given that the Workrave window doesn't stay open (disappears within a few seconds) and accessing it from the applications menu also doesn't work ("Workrave failed to start. Is Workrave already running?"), the only way to access the settings is to kill Workrave, start it again and right-click the window to access the menu before the window disappears.

**To Reproduce**
Install the latest version of Workrave on Ubuntu 18.04.5 LTS from the PPA. Start Workrave if not already running. Check system tray.

**Expected behavior**
Workrave icon appears in the system tray.

**Screenshots**
![image](https://user-images.githubusercontent.com/8046580/104703672-ebfca700-5717-11eb-9339-033da998728e.png)

**Linux**
 - Distribution: Ubuntu
 - Distribution Version: 18.04.5 LTS
 - Desktop Environment: GNOME/Unity
 - Workrave Version 1.10.44-ppa1~bionic1

**Comment by rcaelers** [comment]
GNOME removed support for status icons in 3.26 it seems (see their [blog](https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/)). Other desktop environments may still support status icons. Workrave is not aware of the desktop environment you are using; so it will just enable the status icon and depending on the desktop environment it will be visible or not. Maybe some Gnome Shell extension can be used to bring the status icons back. Not sure if I can easily detect whether status icons are supported. Also, Gtk3 deprecated support for status icons, so Workrave will at some point also drop support for status icons.

The disappearing main window is a known issues and will be fixed in 1.10.45.

For now, you could enable the Workrave applet (see https://workrave.org/docs/applets/gnome/) to make sure you can always access Workrave.

**Comment by cifkao** [comment]
Thanks, that fixed it! A missing piece of information was that I had to install `workrave-gnome` (it would be great to mention in the documentation that this package exists) for the extension to appear in the tweak tool.

> GNOME removed support for status icons in 3.26 it seems

Interesting, I have GNOME 3.28 and still see icons from Slack, VLC and Zoom.

**Comment by rcaelers** [comment]
Thanks for the feedback. I have updated the documentation on the website to mention that you have to install an extra package if you are using the Workrave PPA. 

I checked VLC, it seems it uses the Qt5 QSystemTrayIcon which supports multiple techniques to display a status icon. In case of Gnome/Unity it is probably using the [StatusNotifierItem specification](http://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem). I also have a request to add support for XAppStatusIcon for Cinnamon (#155). So it seems there are at least 3 ways to display a status icon on Linux (depending on desktop environment).....

I will keep this issue open to investigate StatusNotifierItem.

**Comment by wolftune** [comment]
I think this is resolved, see my note at https://github.com/rcaelers/workrave/issues/333#issuecomment-1319077180

**Comment by rcaelers** [comment]
Created separate issue for StatusNotifierItem. Se closing this one.

**Comment by Chealer** [comment]
Thank you very much for reporting @cifkao 
I recommend retitling this to something like:
> Tray icon does not appear on GNOME (since 3.26)

Given that configuring Workrave is not possible/simple without the tray icon, I recommend to display a dialog recommending the user to install either the TopIcons extension or the Workrave applet, unless that is already done, when first running Workrave on GNOME.

It would also clarify a lot to document GNOME’s case in [the _Tray icon_ page](https://workrave.org/docs/menus/tray-icon/).

<details>
  <summary>License</summary>
This comment and any other from myself on this ticket is offered under the terms of CC0 1.0.
</details>

**Comment by Chealer** [comment]
@tukanos has the tray icon on GNOME 49. He attributes that to usage of [the _AppIndicator and KStatusNotifierItem Support_ extension](https://extensions.gnome.org/extension/615/appindicator-support/), which Debian packages as [`gnome-shell-extension-appindicator`](https://packages.debian.org/search?keywords=gnome-shell-extension-appindicator).
