### ISSUE TITLE
timer pauses randomly 

### ISSUE THREAD

**Issue by gold1n89** [rcaelers/workrave#266]
I seem to have this issue where the timer will pause and stop the countdown somewhat randomly. The is no issue with the system clock. I do however have an issue with the display-manager. I am using lightdm as the default. I have to restart it every time I login otherwise the desktop environment behaves abnormal. Do you think these issues could be related? Are there log files etc. or information I could gather to debug this further? I really REALLY need workrave to work :(

**Comment by rcaelers** [comment]
Workrave should start and stop the timers based on your activity. When you start using keyboard/mouse the timers should start, and when you stop using keyboard/mouse the timers should stop a few seconds later. 

Is Workrave stopping timers while you are active, and starting timers when you are nor using the computer?

I transferred this issue from the website repository, so you didn't get the issue termplate. So some questions:

What OS are you using ? Windows? Linux.
In case of Linux: what desktop environment are you using? Gnome, XFCE, Cinnamon, .....
What version of Workrave are you using?

**Comment by gold1n89** [comment]
Ah I see. that makes perfect sense because I use it for reading a lot of the time. I just selected reading mode and the issue seems to be resolved. I will close this out now. thanks!
