### ISSUE TITLE
Add setting disable monitoring

### ISSUE THREAD

**Issue by kostazol** [rcaelers/workrave#270]
Hello. 

I use your software for making breaks for my eyes. Because of it I want to disable activity-monitoring by mouse. I can use my PC without using my mouse. Can you add this setting?

**Comment by rcaelers** [comment]
You want to disable activity monitoring for the mouse and keep monitoring the keyboard? 

Did you try the reading mode? When reading mode is turned on, Workrave will only use activity monitoring to start the timers initially, then Workrave will show periodic microbreaks until you have a restbreak. After the restbreak, any activity will restart this process.

**Comment by kostazol** [comment]
Oh, it is great! I didn't find information about Reading mode before. Thank you, this is what I need. Maybe can you add link to manual in your program?

**Comment by rcaelers** [comment]
It is already in the manual :-) https://workrave.org/docs/menus/reading-mode/. Maybe it is too well hidden in the section about the menus.

**Comment by kostazol** [comment]
Yes, it is already in the manual, but i didn't find link from software. It is also very interesting your software is multilanguage, but the manual has only English version. Your software is great! I wrote what you can make better, but it is not necessarily.
