### ISSUE TITLE
Taskbar

### ISSUE THREAD

**Issue by TMNIrish** [rcaelers/workrave#277]
Workrave taskbar,  2021-02-13,  TMNIrish,  T.M.N.Irish@bcs.org.uk

In Workrave 1.10, which is on my older Windows 10 computer,
the Workrave taskbar shows all three of the timer window's timers.
To be able to see them all on a single row deep toolbar
obviously takes up a lot of space on the the toolbar.
However, I have a three row deep auto-hiding toolbar
and the three timers stack neatly on top of each other.
That is a satisfactory arrangement.

In Workrave 1.10.44, which I have just put on my newer Windows 10 computer,
the Workrave taskbar shows only one of the timers at a time,
and cycles round them roughly every ten seconds.

Might it be not too difficult please to add an option
to allow a choice of which of these two behaviours is used ?
Obviously I would prefer to use the older behaviour.

**Comment by kees-jan** [comment]
Kindly open the "Preferences" window, and then navigate to "User interface", "Applet" tab.
![image](https://user-images.githubusercontent.com/221402/107955915-af360100-6f9e-11eb-8bd9-813c0b080b13.png)

**Comment by rcaelers** [comment]
I am closing this issue because I believe this is indeed already possible.
Please re-open this issue if you did not manage to get the behavior from your older Windows 10 computer back.
