### ISSUE TITLE
No groovy release in PPA

### ISSUE THREAD

**Issue by lorrin** [rcaelers/workrave#280]
**Describe the bug**

The PPA ppa:rob-caelers/workrave currently has no entry for groovy, making it difficult to use the PPA on Ubuntu 20.10 and derivatives. 

**To Reproduce**
Attempting to add the PPA results in an error about there not being a release file.

```
Fehl:17 http://ppa.launchpad.net/rob-caelers/workrave/ubuntu groovy Release 
  404  Not Found [IP: 91.189.95.85 80]
Paketlisten werden gelesen… Fertig
E: Das Depot »http://ppa.launchpad.net/rob-caelers/workrave/ubuntu groovy Release« enthält keine Release-Datei.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
```

I tried [forcing use of](https://askubuntu.com/questions/293203/how-can-i-add-a-ppa-from-a-previous-release) the focal release instead, but bumped into an unsatisfied dependency on libpanel-applet3 (>= 3.2.1)

**Linux (please complete the following information in case you encountered the bug on Linux):**

 - Distribution: Pop!_OS
 - Distribution Version: 20.10
 - Desktop Environment: Gnome

**Comment by rcaelers** [comment]
Indeed. No new Workrave version has been released since the release of Groovy. So the version in Groovy is already the latest version. Version 1.10.45 (to be released soon) will also have Groovy and Hirsute in the PPA.

**Comment by rcaelers** [comment]
1.10.45 has been released with Groovy package.
