### ISSUE TITLE
WR gnome extension crashes on start and disables all other extensions

### ISSUE THREAD

**Issue by samminor** [rcaelers/workrave#281]
**Describe the bug**
Start of workrave-gnome disables all gnome-shell extensions.

**To Reproduce**
1. $ sudo apt install workrave-gnome
2. Add workrave to startup applications
3. Log out, log in

**Expected behavior**
Workrave icon at the tray and proper work of my gnome shell extensions.

**Screenshots**
![Screenshot from 2021-02-24 11-23-12](https://user-images.githubusercontent.com/2834898/108978823-b5109e00-7692-11eb-8d35-842fd2273a48.png)

**Linux**
 - Distribution: Ubuntu 
 - Distribution Version: 20.04.2 LTS
 - Desktop Environment: GNOME Shell 3.36.4
 - Workrave Version 1.10.44-ppa1~focal1 (also affects 1.10.37 from main repository)

**Additional context**
Workrave works after bug, but without tray icon:
`sam@ipotseluev-host:~$ ps axf | grep workrave
  64547 ?        SLl    0:03  |   \_ /usr/bin/workrave
`
syslog:

```
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: JS ERROR: Could not load extension system-monitorparadoxxx.zero.gmail.com.v39.shell-extension: Error: uuid "system-monitor@paradoxxx.zero.gmail.com" from metadata.json does not match directory name "system-monitorparadoxxx.zero.gmail.com.v39.shell-extension"#012createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:306:19#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:594:34#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17#012_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:574:19#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:608:18#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18#012init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14#012_initializeUI@resource:///org/gnome/shell/ui/main.js:257:22#012start@resource:///org/gnome/shell/ui/main.js:146:5#012@<main>:1:47
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: workrave-applet: start @ 35102788
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: Can't create a GtkStyleContext without a display connection
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: GNOME Shell crashed with signal 5
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: == Stack trace for context 0x55eaeaccc2a0 ==
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: #0   55eaeb20bfb0 i   /usr/share/gnome-shell/extensions/workrave@workrave.org/extension.js:62 (3dd071baa448 @ 61)
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: #1   55eaeb20bf00 i   resource:///org/gnome/gjs/modules/script/_legacy.js:82 (315f596a9970 @ 69)
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: #2   55eaeb20be50 i   /usr/share/gnome-shell/extensions/workrave@workrave.org/extension.js:355 (3dd071baa3d0 @ 41)
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: #3   7fff5f6ba140 b   resource:///org/gnome/shell/ui/extensionSystem.js:167 (38aae1646a0 @ 571)
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: #4   55eaeb20bd88 i   resource:///org/gnome/shell/ui/extensionSystem.js:349 (38aae164bc8 @ 361)
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: #5   55eaeb20bca0 i   resource:///org/gnome/shell/ui/extensionSystem.js:599 (38aae16a718 @ 551)
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: #6   7fff5f6bb030 b   resource:///org/gnome/shell/misc/fileUtils.js:27 (38aae1068f8 @ 350)
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: #7   55eaeb20bbf8 i   resource:///org/gnome/shell/ui/extensionSystem.js:574 (38aae16a6a0 @ 494)
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: #8   55eaeb20bb68 i   resource:///org/gnome/shell/ui/extensionSystem.js:608 (38aae16a790 @ 67)
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: #9   55eaeb20bad8 i   resource:///org/gnome/shell/ui/extensionSystem.js:639 (38aae16a970 @ 57)
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: #10   55eaeb20ba18 i   resource:///org/gnome/shell/ui/extensionSystem.js:56 (38aae164358 @ 268)
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: #11   55eaeb20b978 i   resource:///org/gnome/shell/ui/main.js:257 (315f596d5cb8 @ 1181)
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: #12   55eaeb20b8c8 i   resource:///org/gnome/shell/ui/main.js:146 (315f596d5ad8 @ 308)
Feb 24 09:48:39 ipotseluev-host gnome-shell[2069]: #13   55eaeb20b840 i   <main>:1 (315f5968d178 @ 48)
Feb 24 09:48:40 ipotseluev-host gnome-shell[2096]: (EE) could not connect to wayland server
Feb 24 09:48:40 ipotseluev-host systemd[1916]: gnome-shell-wayland.service: Main process exited, code=dumped, status=5/TRAP
Feb 24 09:48:40 ipotseluev-host systemd[1916]: gnome-shell-wayland.service: Failed with result 'core-dump'.
Feb 24 09:48:40 ipotseluev-host systemd[1916]: Failed to start GNOME Shell on Wayland.
Feb 24 09:48:40 ipotseluev-host systemd[1916]: Dependency failed for GNOME Shell on Wayland.
Feb 24 09:48:40 ipotseluev-host systemd[1916]: Dependency failed for GNOME Wayland Session.
Feb 24 09:48:40 ipotseluev-host systemd[1916]: Dependency failed for GNOME Wayland Session (session: ubuntu).
Feb 24 09:48:40 ipotseluev-host systemd[1916]: gnome-session-wayland@ubuntu.target: Job gnome-session-wayland@ubuntu.target/start failed with result 'dependency'.
Feb 24 09:48:40 ipotseluev-host systemd[1916]: gnome-session-wayland.target: Job gnome-session-wayland.target/start failed with result 'dependency'.
Feb 24 09:48:40 ipotseluev-host systemd[1916]: gnome-shell-wayland.target: Job gnome-shell-wayland.target/start failed with result 'dependency'.
Feb 24 09:48:40 ipotseluev-host systemd[1916]: gnome-shell-wayland.service: Triggering OnFailure= dependencies.
Feb 24 09:48:40 ipotseluev-host systemd[1916]: unicast-local-avahi.path: Succeeded.
Feb 24 09:48:40 ipotseluev-host systemd[1916]: Stopped Path trigger for Avahi .local domain notifications.
Feb 24 09:48:40 ipotseluev-host systemd[1916]: update-notifier-release.path: Succeeded.
Feb 24 09:48:40 ipotseluev-host systemd[1916]: Stopped Path trigger for new release of Ubuntu notifications.
Feb 24 09:48:40 ipotseluev-host systemd[1916]: Started Disable GNOME Shell extensions after failure.
```

**Workaround:**
Remove workrave shell extension

**Comment by rcaelers** [comment]
When the Gnome-Shell extension is enabled, Workrave will automatically start when you log in. No need to add Workrave to the startup applications.

That said: I managed to reproduce the issue. Based on a comment in a Mutter bug report (https://gitlab.gnome.org/GNOME/mutter/-/issues/1475#note_1024023), I expect that the Workrave extension gets activated too soon because Workrave is also started sooner. When the Workrave extension is activated, Mutter has not yet initialized Gtk and therefore the extension cannot retrieve the colors of the selected theme. And that causes the crash. Calling Gtk in a Gnome Shell extension is apparently "not done". So after the release of 1.10.45 I will do some refactoring in the extension.

**Comment by tjyrinki** [comment]
FWIW I've had the problem for some half a year at least on my openSUSE Tumbleweed. My stack trace:

workrave-applet: start @ 27790217
Can't create a GtkStyleContext without a display connection
== Stack trace for context 0x558a49c4e180 ==
#0   558a49eb4b10 i   /usr/share/gnome-shell/extensions/workrave@workrave.org/extension.js:165 (3d35855f1dd0 @ 61)
#1   558a49eb4a60 i   resource:///org/gnome/gjs/modules/script/_legacy.js:82 (162256991a0 @ 69)
#2   558a49eb49b0 i   /usr/share/gnome-shell/extensions/workrave@workrave.org/extension.js:486 (3d35855f15b0 @ 41)
#3   7ffeba9279d0 b   resource:///org/gnome/shell/ui/extensionSystem.js:167 (1826cd937a10 @ 577)
#4   7ffeba928170 b   resource:///org/gnome/shell/ui/extensionSystem.js:348 (1826cd9376f0 @ 361)
#5   7ffeba928250 b   resource:///org/gnome/shell/ui/extensionSystem.js:586 (1826cd92dfb0 @ 402)
#6   7ffeba928340 b   resource:///org/gnome/shell/misc/fileUtils.js:27 (162256e5c40 @ 392)
#7   558a49eb4908 i   resource:///org/gnome/shell/ui/extensionSystem.js:565 (1826cd937060 @ 494)
#8   558a49eb4878 i   resource:///org/gnome/shell/ui/extensionSystem.js:595 (1826cd92df60 @ 67)
#9   558a49eb47e8 i   resource:///org/gnome/shell/ui/extensionSystem.js:626 (1826cd92de20 @ 57)
#10   558a49eb4728 i   resource:///org/gnome/shell/ui/extensionSystem.js:56 (1826cd937c40 @ 271)
#11   558a49eb4688 i   resource:///org/gnome/shell/ui/main.js:269 (162256bee20 @ 1152)
#12   558a49eb45d8 i   resource:///org/gnome/shell/ui/main.js:159 (162256bef60 @ 324)
#13   558a49eb4550 i   <main>:1 (16225684100 @ 48)
(EE) could not connect to wayland server

In my case, only extension is enabled, nothing in autostart.

So first login attempt to GNOME always fails, second one succeeds but all extensions are disabled. I've workarounded the problem by running `dconf write /org/gnome/shell/disable-user-extensions false` after logging in...

workrave version is 1.10.44 (workrave-1.10.44-1.2.x86_64, includes the shell extension), and GNOME is 3.38 (but happened also with 3.36).

Regardless, thank you for the awesome app I've used for years!

**Comment by tjyrinki** [comment]
Confirming that 56af818cd3e148069134551aacc7b06043d8541a fixes the issue. The patch is being cherry-picked to openSUSE Tumbleweed by me and seemingly in progress also into the Debian 11.

**Comment by rcaelers** [comment]
Thanks for confirming the fix works!
