### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by millerthegorilla** [rcaelers/workrave#283]
Hi, I love using workrave, but recently I have switched to fedora silverblue for a variety of reasons.

Although I can build software, I can't install it as easily.  I wonder if I might request the creation of a flatpak to be submitted to flathub?

many thanks...

**Comment by millerthegorilla** [comment]
Actually workrave is in the fedora repos, so I have been able to install it using the dnf package manager inside 'toolbox'.  Many thanks.

**Comment by David-Else** [comment]
But it is not available for Centos 8... a flatpak would be great!
