### ISSUE TITLE
Workrave detects activity without keyboard or mouse being touched

### ISSUE THREAD

**Issue by burbilog** [rcaelers/workrave#293]
Some time ago workrave began to think that my computer is always active. Microbreak happens all the time, then notice flashes, etc.

1. Launch workrave
2. Wait without touching keyboard or mouse
3. See microbreak notification, then notification flashes orange and microbreak timer goes -X:XX. Sometimes microbreak happens, it flashes orange and always stays at 0:28 seconds.

Somehow workrave thinks that I'm touching keyboard or mouse. I tried to disconnect keyboard and mouse but the problem is still here.

I discovered this problem with workrave from distro, then I installed PPA and nothing changed. 

I ran xev and there was no mouse or keyboard activity if I don't touch them.

 - Distribution: Ubuntu 
 - Distribution Version: 20.04.2 LTS
 - Desktop Environment: KDE
 - Workrave Version:  1.10.45-ppa5~focal

Any ideas how to debug this problem?

**Comment by rcaelers** [comment]
Workrave 1.10.45 adds a debug option for this.

Could you please open the preferences, and go to the 'Monitoring' tab in the Timers section. Press the 'Debug monitoring' button. A new window should appear that shows some internal state and state changes. Wait a minute or so and copy/paste the content of the debug window and add it to this bug report or mail it to me (there should not be any personal data in the logs)

In the meantime, I will install Ubuntu 20.04 and KDE in a virtual machine.

**Comment by burbilog** [comment]
Well, it seems that problem was with my system. I spent a lot of time installing other keyboard break programs and they behaved like workrave too. Then I ran this:

~~~
while [[ $(xprintidle) -lt 60000 ]]; do
        echo "$(date +%T) $(xprintidle)" && sleep 1;
done
~~~

Idle time did not exceed 30. So, it wasn't workrave's fault.

Mysteriously, the problem is gone after a while, after several reboots and probably an upgrade -- can't remember exactly my actions. I have no idea what happened, probably some update in past broke idling and now it's fixed (I hope). At least I don't see this problem anymore after 3 reboots in row.

**Comment by burbilog** [comment]
I found the culprit: 

~~~
Bus 001 Device 013: ID 1bcf:2701 Sunplus Innovation Technology Inc. HD 720P webcam
~~~

If I use this webcam at least once then idle time stops growing. It seems that webcam somehow creates activity. Skype, vlc, whatever -- after first use of this webcam idle time never exceeds 40. Removing webcam's plug and re-plugging fixes this problem, while computer reboot does not. 

So, it's an issue with this particular webcam (sold as 'Canyon' in Russia).
