### ISSUE TITLE
Modification Request: Add setting for allowing immediate postpone

### ISSUE THREAD

**Issue by winternet-studio** [rcaelers/workrave#301]
I see you have done a change that prohibits you to postpone immediately when a rest break comes up. That is a big problem if you sitting in the middle of something you can't quite right there and then! I understand you really think the user should take at least a little break, but this must at least be something that is configurable.  Some times you are simply not in control of the circumstances.

I see you can add the Skip button but that just makes you skip the entire break then - not desirable.

**Comment by kees-jan** [comment]
It sounds like you have "postpone" and "skip" disabled for microbreaks. If that is true, you won't be able to skip or postpone a restbreak either, for the duration of a microbreak.

If you want to be able to skip or postpone a restbreak immediately, please enable "skip" and "postpone" for microbreaks.

Or am I missing something?

**Comment by winternet-studio** [comment]
I have postpone enabled and skip disabled - for both microbreak and rest break. But now I have been using the new version for a day (the old one I had was from like 2013 I think - I never realized there had been made any updates :) ) and most of the time I can actually postpone a rest break immediately - it's only sometimes that I get a little green bar above the button which has to count down for about 30 secs before the button gets active and I can push. Maybe it's only if I postpone it "too many times" it will finally say "well, now I will force you to take a little break at least".... So the problem is not as critical as I first thought...

**Comment by kees-jan** [comment]
I'm a bit confused by your message. If you have indeed postpone and skip _dis_abled, then why are you now complaining that you in fact cannot postpone nor skip? I would have expected you to complain about the old behavior, which allowed you to postpone and skip, even though you disabled that.

Still feeling like I'm missing something ;-)

**Comment by winternet-studio** [comment]
No, I said postpone is ENabled, skip is DISabled. I have always had the correct buttons according to what I had selected in the preferences but the issue was only that postpone was grayed out for a while sometimes in the rest break.

**Comment by rcaelers** [comment]
Workrave should not gray out the postpone button of the restbreak if the postpone button of the microbreak is enabled in the preferences.
The postpone button of the restbreak should only be grayed out if:
- the 'Show Postpone button' setting of the microbreak is disabled
- the microbreak is overdue
- the microbreak has reached the maximum number of prompts.

Looking at the code, It seems I have mixed up postpone/skip somewhere...
Let me fix that...

**Comment by rcaelers** [comment]
I believe this is fixed now. If you are a Windows user, could you test the build of May 12 from https://workrave.org/snapshots/ ?

**Comment by winternet-studio** [comment]
Thanks! I have installed it now and will let you know if I run into any issue.
