### ISSUE TITLE
Workrave does not open and can't disable sound in notifications

### ISSUE THREAD

**Issue by unseldth** [rcaelers/workrave#307]
I am using workrave v1.10.45 for Windows 10 (64-bit). I can view the notifications and the pop-ups show up but if I try to press the symbol for the mircro break it keeps on moving form top to buttom on my screen and I can't press it. Furthermore, when I press the white sheep nothing happens so I can't change the timer for the breaks and I can't disable the sound for the notifications. Otherwise, I find the application very useful.

**Comment by rcaelers** [comment]
The pop-up you are seeing is the [break reminder window](https://workrave.org/docs/breaks/reminder/). No need to click on it. Just stop using keyboard/mouse and the break will automatically start.

**Comment by rcaelers** [comment]
Does this solve your problem?

**Comment by unseldth** [comment]
Yes, thank you.
