### ISSUE TITLE
[Feature request] - A new break option to lock user input after certain time even if mouse/keyboard not used

### ISSUE THREAD

**Issue by absar** [rcaelers/workrave#317]
First of all thank you for maintaining this useful app.
I have a Feature request for a new break option to lock user input after certain time even if mouse/keyboard are not used at all. Current options are good for RSI but are not good for screen and sitting time habits, as often we are in front of the screens but not actively using keyboard/mouse e.g. reading, switching between VMs, watching something etc.
With current options I can not set something like, must stop using the computer every hour for 2 minutes, since the "Rest break" will reset after not using keyboard/mouse for 2 minutes.

**Comment by kees-jan** [comment]
Have you tried activating reading mode?

**Comment by absar** [comment]
Thanks for the info, will try that and come back whether it fulfills the request

**Comment by absar** [comment]
Closing the issue, since reading mode fulfills what I need.

**Comment by kees-jan** [comment]
Hi,
If you have a moment to spare, I'd like to have your advice.

Your request is by no means an incident. Many people want the same feature you do, and many have trouble finding "reading mode". So now my question to you is: What could we have done differently, such that you would have discovered "reading mode" on your own, and gave it a try?

Thanks very much!

**Comment by absar** [comment]
Thanks for being open to critique. I think the first place users would expect to discover it is in the preferences, but it is nowhere there, it would be nice to add another tab in the interface which should include Reading Mode and other options like quiet mode, suspended, exercises, and Statistics, so that once users open preference for the first time to onboard they will setup and see everything in one place:
![image](https://user-images.githubusercontent.com/1186833/126868288-dabf128b-a03d-4b3b-bb46-d82658698bb7.png)
