### ISSUE TITLE
Issue installing workrave from chocolatey

### ISSUE THREAD

**Issue by glanham-jr** [rcaelers/workrave#319]
**Describe the bug**
When attempting to install the package from `chocolately` from Windows 10, I see that an error occurs saying the remote file doesn't exist, is unauthorized, or is forbidden.

It also seems as though the chocolately listed version of 1.10.1.6 is behind the latest stable of 1.10.45.

**To Reproduce**
1. Have `chocolatey` installed on Windows 10
2. Enter `choco install workrave -y` in the Powershell
3. Receive the error about the file not being found

**Expected behavior**
Workrave is installed as expected

**Screenshots**

** Windows (please complete the following information in case you encountered the bug on Windows):
 - Windows OS: Windows 10 Enterprise
 - WIndows Version: 2009 (OS Build 19043.1110)
 - Workrave Version: 1.10.6

**Additional context**
```
Chocolatey v0.10.15
Installing the following packages:
workrave
By installing you accept licenses for the packages.
Progress: Downloading workrave 1.10.1.6... 100%

workrave v1.10.1.6 [Approved]
workrave package files install completed. Performing other installation steps.
Attempt to get headers for http://downloads.sourceforge.net/project/workrave/workrave/1.10/workrave-win32-v1.10-installer.exe?r=&ts=1457189903&use_mirror=netix failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://downloads.sourceforge.net/project/workrave/workrave/1.10/workrave-win32-v1.10-installer.exe?r=&ts=1457189903&use_mirror=netix'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading workrave
  from 'http://downloads.sourceforge.net/project/workrave/workrave/1.10/workrave-win32-v1.10-installer.exe?r=&ts=1457189903&use_mirror=netix'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://downloads.sourceforge.net/project/workrave/workrave/1.10/workrave-win32-v1.10-installer.exe?r=&ts=1457189903&use_mirror=netix'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.
The install of workrave was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\workrave\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - workrave (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\workrave\tools\chocolateyInstall.ps1'.
 See log for details.
```

**Comment by rcaelers** [comment]
The Chocolatey package is not maintained by me. It seems https://community.chocolatey.org/packages/workrave has information on how to contact the maintainers.

Though it is called version 1.10.1.6, it actually downloads version 1.10 from SF.net. I don't recommend using this old version from 2013.

I will close this issue as won't fix because it is a 3rd party package.

**Comment by glanham-jr** [comment]
It seems like the maintainer has his own repository for managing his NuGet packages, including workrave. 

https://github.com/Claud/chocolatey-packages/tree/master/workrave

Would you be interested if I created a pull request for merging in Chocolatey deployment functionality?

**Comment by rcaelers** [comment]
I don't use Chocolatey myself, but I can imagine it is convenient if you can install all 3rd party software with a single tool. So, yes, go ahead :-)

It seems someone already created a pull request: https://github.com/Claud/chocolatey-packages/pull/13
The repository hasn't been updated for quite a while though....

**Comment by glanham-jr** [comment]
I have a feeling that the repo owner is no longer active. Might as well have the Chocolatey information in the repo its built in.
