### ISSUE TITLE
Not possible to install workrave on Mint 20.2

### ISSUE THREAD

**Issue by Felrave** [rcaelers/workrave#327]
**Describe the bug**
I am unable to install workrave on Linux Mint 20.2 via command sudo apt-get install workrave.
The error message is:

**To Reproduce**
1. Go to 'terminal' and use commands:
'sudo apt-get update'
'sudo apt-get install workrave'
2. See error:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 workrave : Depends: xfce4-panel (< 4.15) but 4.16.2-1~20.04 is to be installed
E: Unable to correct problems, you have held broken packages.

**Expected behavior**
Workrave app should be installed

**Screenshots**

** Linux (please complete the following information in case you encountered the bug on Linux):**
 - Distribution: 
 [System:    Kernel: 5.4.0-80-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 5.0.5 
           wm: muffin dm: LightDM Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal ]

**Comment by rcaelers** [comment]
Are you using the Workrave packages from by Ubuntu PPA? Or the standard Linux Mint packages?

If you're using the standard Mint packages, I suggest you file a bug report with Mint. I do not maintain those packages. Likely some dependency has changes and the Workrave package needs to be rebuilt.

**Comment by Alberth289346** [comment]
I have this problem too, trying to fix the problem gives the following information:
``` sh
$ sudo apt install workrave

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 workrave : Depends: xfce4-panel (< 4.15) but 4.16.2-1~20.04 is to be installed
E: Unable to correct problems, you have held broken packages.
```

``` sh
$ apt list \*xfce4-panel\*
Listing... Done
xfce4-panel-dbgsym/focal 4.14.3-1 amd64
xfce4-panel-dev/focal 4.14.3-1 amd64
xfce4-panel-profiles/uma,uma 1.0.13-0ubuntu2~20.04 all
xfce4-panel/uma,now 4.16.2-1~20.04 amd64 [installed]
```
Thus the new Mint 20.4 (LTS version)  upgraded to `xfce4-panel-4.16,2` while their workrave package requires less than `4.15`.

Don't know where this limit is coming from.

**Comment by strpsp** [comment]
I have the same problem on Linux mint 20.04:
workrave : Depends: xfce4-panel (< 4.15) but 4.16.3-1~20.04 is to be installed

**Comment by rcaelers** [comment]
I expect this is an upstream issue in Mint.  So I can't fix this for you.
The Workrave package from my Ubuntu PPA doesn't have a dependency on xfce. My PPA has moved XFCE support into a separate package called workrave-xfce.

**Comment by rcaelers** [comment]
I expect this is an upstream issue in Mint.  So I can't fix this for you.
The workrave package from my Ubuntu PPA doesn't have a dependency on xfce. My PPA has moved XFCE support into a separate package called workrave-xfce.
