### ISSUE TITLE
Time countdown will be stuck

### ISSUE THREAD

**Issue by zhang-chuanfeng** [rcaelers/workrave#330]
**Describe the bug**
Time countdown will be stuck.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59160162/131109748-c596719a-8492-4a3e-b425-66a1430d655d.png)

** Windows (please complete the following information in case you encountered the bug on Windows):
 - Windows Version: [Windows 10]
 - Workrave Version [v1_10_48]

**Additional context**

**Comment by rcaelers** [comment]
I expect by "stuck" you mean the timer does not count down when you start using the computer (i.e. the blue bar does not become larger). Does the timer still count "idle" time? (i.e. does a green bar appear that shows your idle time when you are not using your computer for a while)_

Is the operation mode of Workrave set to "normal"? Or is it set to "suspended"?

If set to "normal", could you open the preferences, go to timers, monitoring and click "Debug monitoring". Then move the mouse for a while (at least 10 seconds) and copy & paste the content of the window in this bug report.

**Comment by zhang-chuanfeng** [comment]
The operation mode of Workrave set to "normal", if I don't move the mouse for more than 10 seconds, the time count will stop. This is not ideal, if I do not operate the mouse, but I am facing the computer screen.

**Comment by kees-jan** [comment]
When you are not operating the mouse (or the keyboard) for more than 10 seconds, countdown is supposed to stop.

You might want to try selecting "Reading mode" from the menu.

**Comment by zhang-chuanfeng** [comment]
ok，thank you.
