### ISSUE TITLE
[New feature request] Setting the duration of inactivity

### ISSUE THREAD

**Issue by dev-hemul** [rcaelers/workrave#341]
Please add a setting that would be responsible for the duration of inactivity
So that I could choose how long it takes for the counter to stop

Windows 10

**Comment by Konzertheld** [comment]
Looks like a duplicate of #120.

**Comment by rcaelers** [comment]
I agree that this is a duplicate. So I will close this one.

**Comment by rcaelers** [comment]
Duplicate of #120.

**Comment by rcaelers** [comment]
Duplicate of #120.
