### ISSUE TITLE
Lack of version number in registry interferes with proper winget behaviour

### ISSUE THREAD

**Issue by Quitch** [rcaelers/workrave#349]
**Describe the bug**
A lack of the "DisplayVersion" REG_SZ, or "Version", "VersionMajor", and "VersionMinor" REG_DWORDs within `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Workrave_is1` means that Microsoft's Windows Package Manager (winget) registers the version of WorkRave as "Unknown" and will always attempt to upgrade it.

**To Reproduce**
1. Install "App Installer" from the Microsoft Store
2. Open a command prompt or PowerShell terminal
3. "winget list workrave"

**Expected behavior**
Version column will show currently installed version of WorkRave

**Screenshots**
![image](https://user-images.githubusercontent.com/5182715/137028039-6114646a-6d10-404c-89f6-1437c4d1d868.png)

** Windows (please complete the following information in case you encountered the bug on Windows):
 - Windows Version: Windows 10 21H1
 - Workrave Version 1.10.48

**Additional context**
https://github.com/microsoft/winget-cli/issues/1255#issuecomment-902873661

**Comment by anaurelian** [comment]
Do you know when this fix is going to be implemented in a public release? Thank you

**Comment by rcaelers** [comment]
I just released 1.10.49 which contains this fix.

**Comment by anaurelian** [comment]
Thank you, I've also closed the related issue in [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs/issues/31007)
