### ISSUE TITLE
Gnome applet not compatible with gnome 40

### ISSUE THREAD

**Issue by croftdynamics** [rcaelers/workrave#352]
I'm using gnome 40 and I'm unable to switch on the workrave applet. It complains that the extension is not compatible with the current gnome version.

**Comment by jacksongoode** [comment]
Here's a solution to quickly try unsupported extensions:
```gsettings set org.gnome.shell disable-extension-version-validation "true"```

**Comment by rcaelers** [comment]
The next release (1.10.50) will support GNOME up to version 42.
