### ISSUE TITLE
Backward shoulder stretch description incorrect

### ISSUE THREAD

**Issue by Quitch** [rcaelers/workrave#354]
**Describe the bug**
The Backward shoulder stretch instructs you to repeat the exercise twice, meaning you perform it three times, but the repeat notification sound/bell only has you perform the exercise twice.

**To Reproduce**
1. Trigger a break
2. Switch to the Backward shoulder stretch exercise

**Expected behavior**
Either:
a) the repeat timer/bell sounds twice instead of once
b) the description reads "repeat once" or "perform twice" instead of "repeat twice"

** Windows (please complete the following information in case you encountered the bug on Windows):
 - Windows Version: Windows 10 21H1
 - Workrave Version 1.10.48

**Comment by rcaelers** [comment]
I implemented option a) The bell sounds twice now. Will be available in 1.10.50.
