### ISSUE TITLE
GNOME applet is positioned too high in menu bar

### ISSUE THREAD

**Issue by jacksongoode** [rcaelers/workrave#356]
**Describe the bug**
![image](https://user-images.githubusercontent.com/54308792/142301487-da6a79ae-b30a-4240-a127-23e9e20b1393.png)

**To Reproduce**
Fedora 35, install Workrave and enable extension

**Expected behavior**
Applet should be lower vertically

** Linux (please complete the following information in case you encountered the bug on Linux):**
 - Distribution: Fedora
 - Distribution Version: 35 
 - Desktop Environment: GNOME
 - Workrave Version: Latest

**Comment by rcaelers** [comment]
Vertical alignment will be fixed in the next release (1.10.50)
