### ISSUE TITLE
Suggestion: Change default sound theme to "Subtle"

### ISSUE THREAD

**Issue by mckaymatt** [rcaelers/workrave#362]
This is a fantastic tool which has been a real live-saver, and I hope you find this user experience / suggestion helpful.

The "Default" sound theme is punchy and I find it a bit grating after a while. I also hear a popping and hissing sound before the Default sounds play, which I don't hear with the Subtle theme. I pulled the repo and played the wav files directly but don't hear this popping, so I assume it's something to do with my audio (on both Fedora and Ubuntu). Either way, it the Subtle theme does not seem to have this issue.

The Subtle theme also has a more modern, pleasing sound, and IMO it would be a better default setting for new users. 

Thanks for making this by the way!

**Comment by rcaelers** [comment]
Sounds like a good idea! Suggestions for a new name for the "Default" sound theme are welcome :-)

**Comment by mckaymatt** [comment]
> Suggestions for a new name for the "Default" sound theme are welcome :-)

It looks like it's already displays on the dropdown as `Classic`. Maybe just officially make default > Classic everywhere.

**Comment by rcaelers** [comment]
The subtle sound theme will be the new default in Workrave 1.11.
