### ISSUE TITLE
Workrave dependencies on Windows?

### ISSUE THREAD

**Issue by teknowledgist** [rcaelers/workrave#367]
I'm trying to get an automated install of Workrave onto a bare-bones, really-old remote system, and it seems to fail with an error 5.  It works great on all the more modern, patched, etc. systems I test it on (to which I also have direct access).

Since Workrave appears to be compatible all the way back to WinXP, I'm guessing there is some kind of library dependency that this remote system is missing.  The installer might even be reporting that, but I can't see it.

I'm fine with installing additional libraries as needed, but I also need to know what those are.  Thanks!

**Comment by teknowledgist** [comment]
Logging into a bare-bones 2012r2 system and attempting to install WorkRave manually gives me this near the end of the install:

![InstallFail](https://user-images.githubusercontent.com/3977744/147715090-b003c6cd-7f34-4980-90ee-156a1c3062bc.png)

The binaries appear to all be in the `C:\Program Files (x86)` and the Start Menu shortcut is there, but it all gets reverted if you cancel.  If you "ignore" the error, WorkRave does launch and appears to work at first glance.  The problem is, I need to be able to install this silently and without user interaction.

Since this works fine on newer Windows systems and I don't find reports of it failing on other older versions of Windows, I have to assume that it is a dependency issue.  Please let me know what dependency it has so I can install that first.

**Comment by rcaelers** [comment]
I am not aware of any additional libraries needed. I don't have access to an XP system, unfortunately. So I can't test this.

The error is caused by not having administrator rights that are required to register the applet. You can safely ignore the error and continue installation. Workrave will be functional, except the taskbar applet.

You can add some options to the installer to make it silent: https://jrsoftware.org/ishelp/index.php?topic=setupcmdline.

**Comment by teknowledgist** [comment]
It can't be an administrator rights issue because I get that error running the installer as admin.  

[I have some experience with silent installs](https://community.chocolatey.org/packages/workrave) and [know about the option](https://github.com/teknowledgist/Chocolatey-packages/blob/master/automatic/workrave/tools/chocolateyinstall.ps1).  😄 

The problem is the verification system in place for Chocolatey is completely automatic.  There is no "ignore the error and continue" option.  The silent install either works or doesn't, and it is tested on a (IMHO, ridiculously) outdated system.  You might notice that previous releases did work.  It's only this latest one that is giving the error.

I'll see if I can poke "deeper" to better identify the source of the issue, but if you have any inspirations, I'm happy to test beta installers.

**Comment by teknowledgist** [comment]
Just for reference, v1.10.44 installs just fine on the older 2012r2 system.  Version 1.10.45 has the same error on that older system that v1.10.48 and v1.10.49 have above.  

I don't know if it helps because nobody wants to look at code from almost a year ago, but whatever is causing the error was introduced in v1.10.45.

**Comment by rcaelers** [comment]
I found a 2012r2 download on Microsoft's website and managed to reproduce this. In 1.10.45 I switched to Visual Studio 2019 for compiling the applet. The previous versions were compiled with Visual Studio 2015. I am trying to change the build to support Windows 8.1 and up (WINVER >= 0x603), but it seems the applet now uses a function (GetDpiForWindow) that requires Windows 10. I will change the applet to check at runtime if this function is available.

**Comment by rcaelers** [comment]
The latest 1.10 build from https://workrave.org/snapshots/ should install correctly on Windows 2012r2. The fix will also be in Workrave 1.10.50. 

Please re-open this issue oiff my fix doesn't solve the issue for you.

**Comment by teknowledgist** [comment]
I'm getting the same error with the 1.10.49+445commits download.

**Comment by teknowledgist** [comment]
I don't know how to re-open the issue (or don't have rights).

**Comment by rcaelers** [comment]
1.10.49+445 commits is the upcoming 1.11 release. It will soon be tagged as 1.11-alpha1. This version will for sure not work on 2012r2. Please try the 1.10 release (1.10.49  + 13)

**Comment by DeronLJ** [comment]
I can confirm that the warning no longer shows up when installing v1_10_49-13 on Windows 7. Thank you!

**Comment by rcaelers** [comment]
Thanks for the feedback!

**Comment by teknowledgist** [comment]
Ah!  Sorry, I misunderstood what to download for testing.  I have also now confirmed that the 1.10.49-13commits installer works flawlessly on the older system.  Since it is a pre-release, I'm going to hold off on submitting an updated package to the Chocolatey public repository, but I will as soon as 1.10.50 is officially available.

Thanks!
