### ISSUE TITLE
[Feature Request] Option to disable return/space key

### ISSUE THREAD

**Issue by asrcpq** [rcaelers/workrave#368]
workrave 1.10.48
Debian sid
i3wm 4.20

When switching between floating windows in i3wm I often accidentally press the return/space key which starts a rest break immediately.

I wish there would be an option to disable these keys, since I can always manually start a rest break by right-clicking the tray icon.

**Comment by rcaelers** [comment]
Keyboard focus on now disabled for the "restbreak now" button. The next version (1.10.50) will contain this change
