### ISSUE TITLE
Workrave applet extension shows incompatible on Fedora 35

### ISSUE THREAD

**Issue by thoraxe** [rcaelers/workrave#370]
**Describe the bug**
After reinstalling Fedora to version 35, the Workrave applet indicates it is incompatible with Gnome 41.2

**To Reproduce**
1. Login
2. Open Gnome extension manager

**Expected behavior**
Workrave applet should show it is functional

**Screenshots**
![Screenshot from 2021-12-15 17-06-53](https://user-images.githubusercontent.com/94413/146272995-c541cb17-2c8c-47b9-9598-947c23d40299.png)

** Linux (please complete the following information in case you encountered the bug on Linux):**
 - Distribution: Fedora
 - Distribution Version: 35 
 - Desktop Environment: gnome-shell-41.2-1.fc35.x86_64 
 - Workrave Version workrave-1.10.45-2.fc35.x86_64

**Comment by WhiteCzar** [comment]
Same shit on Ubuntu 21.10. I think it's the GNOME 40+ that's at fault here. The applet doesn't have a GNOME 40+ version.

**Comment by WhiteCzar** [comment]
Oh hey, look at the release page:

Workrave 1.10.48 has been released. This release fixes the GNOME Shell applet on GNOME Shell 3.30 and older.

    Fixed GNOME Shell applet on Ubuntu 18.04 (#281)

I think maybe you might have an old version of Workrave in your Fedora repository. Ubuntu 21.10 does have an old version. I'll try installing the latest version and will tell you if this helps.

**Comment by WhiteCzar** [comment]
Alright, I installed the newest version with a PPA and the applet is working just fine. You need to find a way to install the latest version on your Fedora installation somehow. (Perhaps a tarball? Haha)

**Comment by rcaelers** [comment]
Workrave 1.0.49 should support GNOME 41 (tested on Fedora 35)

**Comment by igor-kobzev** [comment]
Did you install it from source or is there a package for Fedora already?

**Comment by igor-kobzev** [comment]
If you have to install it from source, is there a manual how to do that?

**Comment by rcaelers** [comment]
Installed from source. There is some generic documentation in https://github.com/rcaelers/workrave/blob/branch_v1_10/INSTALL. Basically, you have to install a lot of -devel/-dev packages and then:

./configure --prefix=INSTALL_LOCATION
make install
