### ISSUE TITLE
Right mouse click on windows system tray icon is often not open menu

### ISSUE THREAD

**Issue by Manni79** [rcaelers/workrave#373]
Hello,

when I use right mouse button to click on windows system tray icon of Workrave, the context menus very often not opening. Most of the time I have to click first left mouse button followed by right mouse button to open the menu.

I tested all other tray icons on my windows tray icon list. but all other icons are working fine. On right mouse button click all other context menus open directly. So, I think it's related to Workrave.

- Windows 10
- Newest Patchlevel

Thanks a lot

**Comment by rcaelers** [comment]
This issue will be fixed in upcoming Workrave 1.11 (Workrave 1.11 will use native Windows menus instead of Gtk+ menu for the tray icon)
