### ISSUE TITLE
Installation from user mode

### ISSUE THREAD

**Issue by unseldth** [rcaelers/workrave#379]
I really like the application and I use it on my private notebook. However, in my workplace i don't have administrator rights and the installation fails. Is there a possiblity to install workrave from user mode?

Thank you very much for your reply.

**Comment by rcaelers** [comment]
Workrave requires admin rights to install and register the Windows Applet. If you don't have admin rights, you will indeed get an error during installation. You can click "ignore" and continue the installation when you get this error. 

The next version of Workrave (1.10.50) should skip the Applet when you don't have admin rights.

Until 1.10.50 is released, the latest 1.10 snapshot build can be downloaded from https://workrave.org/snapshots/
