### ISSUE TITLE
How to parse statistics?

### ISSUE THREAD

**Issue by douglasg14b** [rcaelers/workrave#381]
I'm trying to essentially export my statistic to a more usable format to chart out, but have no idea how this is formatted...

Is there a definition or spec that can be used for parsing this? That clearly describes the data format in an unambiguous manner?

<hr>

Side request: Perhaps it could be stored in a common format like a CSV, JSON, or a button to export as such? Alternatively if I understand the format I could make such a utility others can use to export to their desired format, or insert into their own SQLite DB.

```
WorkRaveStats 4
D 2 7 121 12 45 2 7 121 17 54
B 0 7 4 2 12 0 0 3 194 
B 1 7 0 1 9 0 0 0 0 
B 2 7 0 0 0 0 0 0 0 
m 6 1699 760313 341690 619 474 738 
D 3 7 121 9 24 3 7 121 16 2
B 0 7 23 12 23 1 0 14 1441 
B 1 7 4 0 9 1 1 3 523 
B 2 7 0 0 0 0 0 0 0 
m 6 8029 4728259 2318573 6220 3670 9120 
D 4 7 121 11 1 4 7 121 16 31
B 0 7 16 9 34 0 1 10 1075 
B 1 7 2 1 5 1 0 2 63 
B 2 7 0 0 0 0 0 0 0 
m 6 6112 2379208 1096992 3021 1729 12339 
D 5 7 121 9 53 5 7 121 18 9
B 0 7 32 6 69 6 0 13 3187 
B 1 7 5 1 6 1 0 3 512 
B 2 7 0 0 0 0 0 0 0 
m 6 10649 3231051 1559266 4122 2215 20932 
D 6 7 121 4 0 6 7 121 4 0
B 0 7 0 0 0 0 0 0 0 
B 1 7 0 0 0 0 0 0 0 
B 2 7 0 0 0 0 0 0 0 
m 6 0 0 0 0 0 0 
D 7 7 121 11 54 7 7 121 11 55
B 0 7 0 0 0 0 0 0 0 
B 1 7 0 0 0 0 0 0 0 
B 2 7 0 0 0 0 0 0 0 
m 6 99 112132 33446 59 31 21 
D 11 7 121 15 56 11 7 121 17 37
```

**Comment by rcaelers** [comment]
There is some documentation in https://github.com/rcaelers/workrave/blob/main/contrib/plot/workrave-dump. Let me know if you need further information.

Converting statistics to some other format is on my wishlist. It is likely going to be SQLite.

**Comment by douglasg14b** [comment]
Would you be open to integrations that are not in C? 

For instance an export tool written in C# (.Net 6, portable, cross-platform) for this?

<hr>

I looked through that and I'm still having some issues.



> # D 16 5 104 14 51 17 5 104 3 59
> D(ate):	[ tm_mday tm_mon tm_year tm_hour tm_min ] {2}

I don't think I'm understanding how this is supposed to be  interpreted.  for instance what exactly do you mean by your use of brackets and braces?  There are a lot of ways to interpret that.

* Month Day: 16 
    * Indexing from 1 or 0?
* Month: 5
    * Indexing from 1 or 0?
* Year... 104?
* Hour: 14
* Minute: 51
* ??? 17
* ??? 5
* ??? 104
* ??? 3
* ??? 59

**Comment by rcaelers** [comment]
The D contains the start and end time, so {2} means: repeat text between [] twice.

The field names are documented here: https://en.cppreference.com/w/c/chrono/tm
So: 16 5 104 14 51 17 5 104 3 59
Start time June 16th 2004 14:51 
End time: June 17th 2004 3:59

**Comment by douglasg14b** [comment]
Ah, wonderful, thanks!

Do you by chance have a particularly large statistics file that you're willing to share?

I suppose I could generate one, but it would be easier if one was already on hand.

**Comment by rcaelers** [comment]
I don't have any statistics files I want to share...  

I think this question is answered (I also enabled the discussions feature from GitHub if you have more questions), so I will close this issue.
