### ISSUE TITLE
Findcrashpad.cmake missing

### ISSUE THREAD

**Issue by 1Jesper1** [rcaelers/workrave#383]
**Describe the bug**
```
"CMake Error at CMakeLists.txt:705 (find_package):
  By not providing "Findcrashpad.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "crashpad",
  but CMake did not find one.

  Could not find a package configuration file provided by "crashpad" with any
  of the following names:

    crashpadConfig.cmake
    crashpad-config.cmake

  Add the installation prefix of "crashpad" to CMAKE_PREFIX_PATH or set
  "crashpad_DIR" to a directory containing one of the above files.  If
  "crashpad" provides a separate development package or SDK, be sure it has
  been installed."
```

Fixed the error by creating an empty Findcrashpad.cmake file in build/cmake/modules

** Windows
 - Windows Version: Windows 10
 - Workrave Version 1.10

**Comment by rcaelers** [comment]
I did not document how to build Workrave with crashpad to avoid crash dump uploads from Workrave versions not build by me. Did you add -DWITH_CRASHPAD=OFF to cmake? That should disable crashpad. I will disable crashpad by default.

**Comment by 1Jesper1** [comment]
Thanks, I had `-DWITH_CRASHPAD=OFF~`.., that was the problem.
