### ISSUE TITLE
Could not find Win32ResolveDependencies

### ISSUE THREAD

**Issue by 1Jesper1** [rcaelers/workrave#384]
**Describe the bug**
```
-- Resolving dependencies. This may take a while
CMake Error at C:/Users/Jesper/Documents/workrave/ui/app/toolkits/gtkmm/dist/windows/InstallDependencies.cmake:13 (include):
  include could not find requested file:

    Win32ResolveDependencies
Call Stack (most recent call first):
  ui/app/toolkits/gtkmm/dist/windows/cmake_install.cmake:882 (include)
  ui/app/toolkits/gtkmm/dist/cmake_install.cmake:42 (include)
  cmake_install.cmake:66 (include)
```

** Windows
 - Windows Version: Windows 10
 - Workrave Version 1.10

**Comment by rcaelers** [comment]
The Win32ResolveDependencies.cmake file should be in build/cmake/modules. Do you have this file?

**Comment by 1Jesper1** [comment]
@rcaelers Yes, the file is there.

**Comment by 1Jesper1** [comment]
@rcaelers do you know how I can fix it?

**Comment by rcaelers** [comment]
Not yet. I haven't been able to reproduce this error. How did you exactly invoke the cmake commands?

**Comment by 1Jesper1** [comment]
Exactly like https://workrave.org/docs/build/windows/

**Comment by rcaelers** [comment]
Somehow, it works fine for me. The instructions contain `<root-dir>`. My guess was that this path is causing the issue (C:\Foo\Bar is /c/Foo/Bar in MinGW). This is what I get:

Workrave checked out in my Documents folder:
```
robc@TEN MINGW64 /c/Users/robc/Documents
$ ls -lad workrave*
drwxr-xr-x 1 robc None 0 Feb 19 14:59 workrave
```

I executed the following commands: (I left out `<root-dir>` because it is the current directory anyway)

```
robc@TEN MINGW64 /c/Users/robc/Documents
$ pwd
/c/Users/robc/Documents

robc@TEN MINGW64 /c/Users/robc/Documents
$ cmake -G Ninja -S workrave -B workrave-build -DCMAKE_TOOLCHAIN_FILE=build/cmake/toolchains/msys2.cmake -DCMAKE_INSTALL_PREFIX=workrave-deploy -DCMAKE_BUILD_TYPE_INIT=Debug -DWITH_TRACING=TRUE -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DWITH_UI=Gtk+3 -DWITH_TESTS=ON -DCODE_COVERAGE=OFF -DWITH_CRASHPAD=OFF

robc@TEN MINGW64 /c/Users/robc/Documents
$ cmake  --build workrave-build/

robc@TEN MINGW64 /c/Users/robc/Documents
$ ls -lad workrave*
drwxr-xr-x 1 robc None 0 Feb 19 14:59 workrave
drwxr-xr-x 1 robc None 0 Feb 19 17:01 workrave-build
```

I removed the Win32ResolveDependencies.cmake file and executed:

```
cmake --install workrave-build
```
This resulted in the following error:

```
-- Resolving dependencies. This may take a while
CMake Error at workrave/ui/app/toolkits/gtkmm/dist/windows/InstallDependencies.cmake:13 (include):
  include could not find requested file:

    Win32ResolveDependencies
Call Stack (most recent call first):
  workrave-build/ui/app/toolkits/gtkmm/dist/windows/cmake_install.cmake:882 (include)
  workrave-build/ui/app/toolkits/gtkmm/dist/cmake_install.cmake:42 (include)
  workrave-build/cmake_install.cmake:66 (include)
```
My output contains workrave-build, which is not the same as your output. That is why I wanted to know the extact cmake command you executed. Your output suggests that you are running `cmake --install .` in the workrave-build directory (or executing `ninja install` directly). Which is normally fine.

**Comment by 1Jesper1** [comment]
Thanks, I will try tonight

**Comment by 1Jesper1** [comment]
@rcaelers It seems the user folder is different for MODULE_PATH
My user folder is "Jesper Laptop"
message(${MODULE_PATH}) = C:/Users/JesperLaptop/Documents/workrave/build/cmake/modules
message(${INSTALL_PATH}) = C:/Users/Jesper Laptop/Documents/workrave-deploy

**Comment by 1Jesper1** [comment]
Fixed it by setting `string(REPLACE ";" "\ " MODULE_PATH "${MODULE_PATH}")`

**Comment by 1Jesper1** [comment]
After cmake --install workrave-build I get `libgcc_s_seh-1.dll not found` and `libboost_serialization-mt.dll was not found`

**Comment by 1Jesper1** [comment]
> After cmake --install workrave-build I get `libgcc_s_seh-1.dll not found` and `libboost_serialization-mt.dll was not found`

Fixed by adding `C:\msys64\mingw64\bin`  to PATH environment variable!

**Comment by 1Jesper1** [comment]
@rcaelers Maybe we should add  workrave-build/* and workrave-deploy/* to .gitignore? I ran the cmake command in the workrave folder and ended up with many changes in the folder :)
Would also be nice to add "C:\msys64\mingw64\bin to PATH environment variable" in the Windows build doc.

**Comment by rcaelers** [comment]
@1Jesper1 : I usually use _build and _deploy. These directories are already in .gitignore. But I don't mind adding workrave-build and workrave-deploy. Not sure about the extension to PATH. "C:\msys64\mingw64\bin" is a windows PATH, not a MinGW PATH. The MinGW equivalent would (probably) be /c/mingw64/bin . Are you running all commands from a MinGW64 shell?

**Comment by 1Jesper1** [comment]
@rcaelers I think you are right about the PATH problem. I try to reproduce it, but it does not give the error. Could be I tried in a non MinGW64 shell before..

**Comment by 1Jesper1** [comment]
@rcaelers Let's close this.
