### ISSUE TITLE
Missing space in Windows statusicon balloon for mode in Dutch language

### ISSUE THREAD

**Issue by 1Jesper1** [rcaelers/workrave#388]
Missing space in Windows statusicon balloon for "mode" in Dutch language

![image](https://user-images.githubusercontent.com/4539406/154858111-6f35015f-7150-48a8-b5b1-844cfec09433.png)

** Windows
 - Windows Version:  Windows 10
 - Workrave Version 1.10

**Comment by WKobes** [comment]
![image](https://user-images.githubusercontent.com/9413731/197512393-e7591660-d01b-4b96-bc81-30f12f553cea.png)

The missing space and semicolon seems fixed, but the disabled mode (Uitgeschakeld) is too long for a single line.

**Comment by 1Jesper1** [comment]
@WKobes Thanks for checking if the problem is fixed! I will close this issue.
