### ISSUE TITLE
[FEATURE] Respect "do not disturb" OS setting

### ISSUE THREAD

**Issue by Quitch** [rcaelers/workrave#398]
**Issue requiring solving**

Workrave does not respect the OSs' "do not disturb" setting (known as Focus Assist in Windows), leading to it interrupting you during periods you have indicated you do not wish to be interrupted. This can cause issues with full screen content and games.

Workrave supports switching to quiet modes, but this requires additional actions separate from automatic OS features.

**Proposed solution**

Add a drop-down box titled "Mode to switch to during Do Not Disturb" and allow selection of everything on the Mode menu on the tray icon's context menu. Default to Quiet.

**Reason for feature**

Prevents Workrave from interrupting at a time you've indicated you do not wish to be interrupted. Does so automatically without Workrave requiring its own steps, and also resolves the issue of forgetting to re-enable Workrave.

**Comment by kees-jan** [comment]
This looks as a duplicate of #226. I recommend you download [a development build (be sure to click the "Workrave 1.11" tab)](https://workrave.org/snapshots/) and give that a try.

**Comment by Quitch** [comment]
Thanks. I didn't think to search by the acronym :)
