### ISSUE TITLE
Pause workrave itself? Options for meetings?

### ISSUE THREAD

**Issue by bsteinberg321** [rcaelers/workrave#407]
Hi,

I spend a lot of time in videoconference meetings. If I leave workrave on, I (and my colleagues) get interrupted by loud (otherwise helpful) break reminder sounds. This has led to me closing the app and usually forgetting to restart it afterwards.

Any potential solutions to this? Some sort of auto-restart after a certain time or a temporary pause on alert sounds or something?

Thanks.

**Comment by kees-jan** [comment]
Yes. Look at #98 for UI examples. The feature hasn't been released yet. I recommend you download [a development build (be sure to click the "Workrave 1.11" tab)](https://workrave.org/snapshots/) and give that a try.

**Comment by bsteinberg321** [comment]
Thanks! Due to security protocols on my work computer I am not able to use the development build versions. Any ETA on when this feature will be officially released?

**Comment by kfbest** [comment]
Is there any way to have Workrave detect if there is an active screenshare occuring? I often forget to set the mode before my meetings and I get popups while presenting.

**Comment by rcaelers** [comment]
As Kees-Jan mentioned, Workrave 1.11 has an option to temporarily switch to quiet or suspended. I expect 1.11 will be released in a couple of months. I think the betas are 1.11 stable enough.

I haven't been able to find a generic way to detect screen sharing, or active meetings.  On Windows, Workrave 1.11 supports Focus Assist / Do not disturb. You can configure Windows to change to "Do Not Disturb" automatically while an application is full-screen.  Workrave can be configured to switch to quiet or suspended when "Do Not Disturb" is active. As far as I know, Windows does not automatically switch to DND during a meeting or when screen sharing. But if you present in full screen mode, Workrave can automatically switch to suspended/quiet.
