### ISSUE TITLE
Feature suggestion: Game mode for Workrave and full screen application detection

### ISSUE THREAD

**Issue by DotNetTester** [rcaelers/workrave#410]
I was thinking that it would be a great new feature for Workrave to detect that I'm playing a game on my computer and automatically go into quiet mode while a full screen computer game or application is running. The workrave dialog interrupts and even crashes some games on Windows. I do change Workrave to quiet mode beforehand but sometimes I do manage to forget. Automatic full screen game (and application) detection would be a great option to have in the Workrave settings.

**Comment by DotNetTester** [comment]
Workrave is the worst with DOSBox and DOSBox-X. I have had some really weird behavior and crashes with both. The classic Tomb Raider games and other games with disappear from the game or crash. There's all sorts of weirdness with games and full screen applications.

**Comment by rcaelers** [comment]
On Windows, Workrave 1.11 (in beta) supports Focus Assist / Do not disturb. You can configure Windows to change to "Do Not Disturb" automatically while an application is fullscreen.  Workrave can be configured to switch to quiet or suspended when "Do Not Disturb" is active. So far, only supported on Windows. I haven't been able to find a standardized API for this on Linux. So I will close this issue as done.

DOSBox uses SDL. SDL injects some activity every 5 section to prevent the screensaver from starting. This can be disabled by settings environment variable SDL_VIDEO_ALLOW_SCREENSAVER to one. E.g:

SDL_VIDEO_ALLOW_SCREENSAVER=1 dosbox
