### ISSUE TITLE
workrave : Depends: xfce4-panel (< 4.15)

### ISSUE THREAD

**Issue by thracyturnix** [rcaelers/workrave#414]
**Describe the bug**

Tried to install from default repo - workrave : Depends: xfce4-panel (< 4.15)
Tried to install from ppa:rob-caelers/workrave

**To Reproduce**
1. Fresh install Mint 20.03 Cinnamon
2. Sudo apt install workrave

OR

4. sudo add-apt-repository ppa:rob-caelers/workrave
5. sudo apt install workrave

**Expected behavior**
Install working copy workrave

**Screenshots**
https://imgur.com/a/L3UBGgR

** Linux (please complete the following information in case you encountered the bug on Linux):**
 - Distribution:MINT ...] 
 - Distribution Version: 20.03 
 - Desktop Environment:Cinnamon, ...]
 - Workrave Version [e.g. 1.10]

** Windows (please complete the following information in case you encountered the bug on Windows):
 - Windows Version: [ Windows 7, Windows 8, Windows 10]
 - Workrave Version [e.g. 1.10]

**Additional context**

**Comment by rcaelers** [comment]
I have re-uploaded Workrave to my ppa when I saw this report.  1.10.50-ppa2 was upload June 30th.
This version can be installed on Ubuntu 22.04
I forgot to close this report...  Please reopen if the problem persists.
