### ISSUE TITLE
Run Workrave on Windows 11

### ISSUE THREAD

**Issue by AHelgoy** [rcaelers/workrave#415]
**Describe the bug**
Workrave cannot be started in Windows 11, versjon 21H2

**To Reproduce**
Start Workrave

**Expected behavior**
Application can not continue because ResampleDmo.DLL is not found.

**Screenshots**

** Linux (please complete the following information in case you encountered the bug on Linux):**

** Windows (please complete the following information in case you encountered the bug on Windows):
 - Windows Version: Windows 11, versjon 21H2
 - Workrave Version 1.10.50

**Additional context**

**Comment by Quitch** [comment]
I'm running Workrave on this version of Windows without issue.

**Comment by rcaelers** [comment]
ResampleDmo.dll is a DLL that provided by Windows. It is not shipped with Workrave. 
When I search for ResampleDmo.DLL on the internet, I see a lot of pages on 'missing ResampleDmo.DLL'.
So this does not seem to be a Workrave issue.
