### ISSUE TITLE
Feature Suggestion: Don Not Disturb For

### ISSUE THREAD

**Issue by yasaman72** [rcaelers/workrave#426]
An option on the taskbar icon to mute the program for a given time. 
The options could be: an hour, two hours, five hours, today

**Comment by Konkrad** [comment]
Hello,
have you had a look at #98 ?

**Comment by rcaelers** [comment]
This feature is available in 1.11.0-alpha.3 (https://github.com/rcaelers/workrave/releases/tag/v1_11_0_alpha_3). 

I will close this issue as a duplicate of #98. If you have any feedback on this feature, please add it to #98.

**Comment by rcaelers** [comment]
Duplicate of #98
