### ISSUE TITLE
GDK-Pixbuf on windows 11 x64 "Entry Point Not Found"

### ISSUE THREAD

**Issue by AlexMKX** [rcaelers/workrave#446]
**Describe the bug**

Before the long break start several windows error messages appear.

**To Reproduce**
1. Restart app
2. Start Long Break
3. Error appears

The procedure entry point DllMain could not be located in the dynamic link library C:\Program Files\Workrave\lib\gdk-pixbuf-2.0\2.10.0\loaders\libpixbufloader-svg.dll. 

** Windows (please complete the following information in case you encountered the bug on Windows):
 - Windows Version: 11 22H2
 - Workrave Version 1.11-alpha 3

**Additional context**
It seems related to the x64/x32 libraries misconfiguration.

Similar issue described here : https://bytemeta.vip/repo/Cimbali/pympress/issues/150

**Comment by rcaelers** [comment]
The gdk-pixbuf-2.0 loader files are not part of the alpha releases. Did you upgrade from a snapshot or downgrade from beta 2?

The installer that is used by Workrave (Inno Setup) does not remove obsolete files on upgrade/downgrade...
Beta 3 will perform an uninstallation before installing the new version.

As a workaround (until beta 3 is released), you can either uninstall Workrave and reinstall alpha 3, or upgrade directly to beta2. This should fix the 'DllMain' error.

**Comment by AlexMKX** [comment]
Thank you. Clean install has fixed the issue for me.
