### ISSUE TITLE
Settings is not available

### ISSUE THREAD

**Issue by Lovelyvon** [rcaelers/workrave#449]
If I right click on the Workrave icon I only see 4 options: open, run as administrator, pin, unpin and properties. The settings option is not present. This makes it impossible to change the breaks to my own preference. 

**To Reproduce**
1. right click on the Workrave icon
2. no settings option is present

**Expected behavior**
I expect the settings option to be present.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/119620183/205123387-e3801513-0424-42fb-bdb6-d975f89bdeb1.png)

** Linux (please complete the following information in case you encountered the bug on Linux):**
 - Distribution: [e.g. Ubuntu, Fedora, Debian, ...] 
 - Distribution Version: 
 - Desktop Environment: [e.g. Gnome, KDE, XFCE, MATE, Cinnamon, ...]
 - Workrave Version [e.g. 1.10]

** Windows (please complete the following information in case you encountered the bug on Windows):
 - Windows Version: [ Windows 7, Windows 8, Windows 10]
 - Workrave Version [e.g. 1.10]

**Additional context**

**Comment by fburolo** [comment]
That doesn't look like the correct menu... But have you tried with "Properties"?
Also, you should give more info about your app version, OS, DE, etc, for anyone to be able to help you.

**Comment by rcaelers** [comment]
This is indeed not the correct menu. You can control Workrave from the system tray (look for a white sheet). See https://workrave.org/docs/menus/tray-icon/.

Windows supports adding tasks to the application menu you showed. But these tasks will also be available when Workrave is not running. This doesn't sound useful to me for Workrave.

**Comment by kees-jan** [comment]
I'm sorry if this is longer than it needs to be. I'm trying to add as much detail as possible. Maybe too much.

**Preparation 1**

In the screenshot you posted earlier, there is an "unpin from taskbar" menu item. Could you please click that? Pinning currently only adds to the confusion.

![afbeelding](https://user-images.githubusercontent.com/119620183/205123387-e3801513-0424-42fb-bdb6-d975f89bdeb1.png)

If the menu item instead reads "pin to taskbar", then don't touch it. That's the correct setting, at least for now
![image](https://user-images.githubusercontent.com/221402/236907717-c194140f-c0d9-4cc1-819b-59ee59473f42.png)

**Preparation 2: Check if workrave is running**

Click the start menu. Start typing "task". Near the top, the "Task manager" should appear. Click it
![image](https://user-images.githubusercontent.com/221402/236908384-09fc7a6b-069c-43c2-b8d1-17c0f72aa025.png)

In the task manager, select the "details" tab, then click the header in the "Name" column to sort all processes by name, and then scroll down to see if workrave is on the list

![image](https://user-images.githubusercontent.com/221402/236909110-0c4de272-5679-4fd3-87d9-e82e4a5d557c.png)

If workrave is on the list, so much the better. If not, once again click on the start menu, start typing "work", and click workrave as soon as it appears. Double check that the task manager now shows the workrave process. After having done that, close the task manager. We won't be needing it any more.

**Locating the status window 1: On your screen**
If you have just started workrave, it might be that the status window just appeared. It is rather small, so you might have to look for it. Also, for you it will probably not be as colorful as the screenshot below, which is what it looks like for me after a days work and ignoring several breaks 😢 

![image](https://user-images.githubusercontent.com/221402/236909971-845d94bd-498f-4577-bebe-0534c77f4fd3.png)

**Locating the status window 2: In the task bar**
It might be that the status window is open, but some other window is on top of it. Look in the task bar (bottom middle of your screen), to see if workrave is there

![image](https://user-images.githubusercontent.com/221402/236911016-cc49e0c9-bf37-4b36-94e4-ea73da353e2f.png)

Once you found it, click on it, and the status window should appear

**Locating the status window 3: The system tray**
If those two attempts failed, then we have to look at the system tray. That is in the bottom right of your screen, between the clock and the up arrow.
![image](https://user-images.githubusercontent.com/221402/236913099-062a23fe-21de-44d6-bfa4-aa48b5063567.png)
Once you found the sheep, right click it, and choose "open". That should give you the status window

**Locating the status window 3b: Hidden in the system tray**
We're slowly moving into more exotic possibilities: The sheep in the system tray might be hidden.
* Left click the up arrow thingy. One or more icons may pop up (for me, there's a bunch of them)
* Locate the sheep icon and right click it
* Select the "open" item. That should give you the status window

![image](https://user-images.githubusercontent.com/221402/236913819-01169b06-e5fe-4fa9-b9c6-3ee44efbf723.png)

**Locating the status window 4: The toolbar**
Exceedingly unlikely: You have enabled the workrave toobar. It should be somewhere near the bottom of your screen, and look like one or more grey rectangles with numbers in them, and icons to the left:
![image](https://user-images.githubusercontent.com/221402/236914737-c46eb073-badb-43c4-91d5-c9d7ba2a47ba.png)
Right click it. A huge menu will appear. Locate the "open" item (probably near the top), and click it.

**Finally: The preferences**
Once you have located the status window, right click anywhere, except the title bar. Then choose "preferences" from the menu that pops up.
![image](https://user-images.githubusercontent.com/221402/236915250-475c20da-11da-415a-8dd6-8d6d854debc4.png)
