### ISSUE TITLE
Questions about workrave in opensuse tumbleweed

### ISSUE THREAD

**Issue by wagrod** [rcaelers/workrave#452]
Hello!

I use opensuse tumbleweed and workrave behaves differently than other linux distros.

First, the installation part, when running zypper install workrave, the system requires several dependencies, which exceed 100MB. 

Second, after installed, the option to change notification sounds does not appear.

I attach the prints of what I reported.

![Screenshot_20221210_100205](https://user-images.githubusercontent.com/13629837/206867770-83b20797-2275-4afa-932d-25c1cc76f5d1.png)
![Screenshot_20221210_133105](https://user-images.githubusercontent.com/13629837/206867776-f23240f0-d086-4b42-996d-2e63addd206a.png)

**Comment by wagrod** [comment]
I use the kde plasma like graphic ambient.

**Comment by fburolo** [comment]
Looks like bad packaging. Whoever made your OpenSUSE Workrave package made it dependant on a lot of unnecessary Cinnamon and Gnome packages. Workrave is GTK, but the main application should be DE-agnostic. At least that's been my experience so far. I've been using it in Kubuntu in the past without any noticable Cinnamon or Gnome dependencies. You should probably look at who's made the package for OpenSUSE and hint them about it.

**Comment by sebix** [comment]
Downstream issue report is at https://bugzilla.suse.com/show_bug.cgi?id=1208812

**Comment by rcaelers** [comment]
The Workrave packages in my Ubuntu PPA have a separate package for each desktop environment. This reduces the number of dependencies that need to be installed.

As I am not responsible for the openSUSE tumbleweed packages and an upstream bug report has been filed, I will close this issue.
