### ISSUE TITLE
Wrong startup entry path

### ISSUE THREAD

**Issue by KKire** [rcaelers/workrave#462]
**Describe the bug**
When enabling "Start Workrave on logon" in Windows, the startup path is wrong and the settings doesnt work. The path set by workrave is "C:\Program" Files\\**lib**\workrave.exe (notice the quotes between Program" Files and 'lib' subfolder).
The correct path should be "C:\Program Files\Workrave\bin\Workrave.exe" (in 'bin' subfolder).

**To Reproduce**
1. Go to Preferences -> User Interface 
2. Click on "Start Workrave on logon"
3. Open Task Manager -> Startup and see the wrong startup path (or in 
"HKCU\Software\Microsoft\Windows\CurrentVersion\Run" in Registry Editor)

**Expected behavior**
The correct path where workrave is installed "C:\Program Files\Workrave\bin\Workrave.exe"

**Windows:**
 - Windows Version: Windows 11 22H2 22621.1105
 - Workrave Version 1.11.0-beta.5

**Additional context**
When installing, the installer correctly sets the startup path but the workrave itself does not.

**Comment by rcaelers** [comment]
Should be foxed in v1.11.0.beta.5
