### ISSUE TITLE
tracking of keystrokes

### ISSUE THREAD

**Issue by ligate500** [rcaelers/workrave#463]
Hi,
Is there a way to eliminate the tracking of a person's keystroke/mouse use? Someone told me about the issue and doesn't want to use Workrave until it stops tracking. Thank you.

**Comment by mhvis** [comment]
@3lm4k3 a similar question was asked recently in #470. Have you tried Reading Mode as suggested there.

**Comment by wolftune** [comment]
@ligate500 in case there's confusion, are you suspecting any sort of direct keylogging or similar? I believe Workrave does *not* track keystroke/mouse use directly. I'm pretty sure it just query's the OS's system input activity status.

**Comment by rcaelers** [comment]
Workrave does not track/store individual keystrokes. It only monitors if you are active or nor.
By default, it indeed queries the OS if the user is active or not. The "alternative" monitor uses a more low level approach, which would allow storing individual keystrokes. But Workrave doesn't monitor or store individual keystrokes.

You can set the operation mode on 'Suspended' if you want to stop tracking activity.

Workrave relies on this activity monitor, so I can't remove it.
