### ISSUE TITLE
Assertion 'GDK_IS_DISPLAY (display)' failed

### ISSUE THREAD

**Issue by wojnilowicz** [rcaelers/workrave#472]
**Describe the bug**
Workrave fails to start.

**To Reproduce**
1. build workrave from sources on Fedora 37 KDE with GTK enabled
2. start workrave in terminal
3. crash

**Expected behavior**
No crash.

**Additional context**
The crash happens in
https://github.com/rcaelers/workrave/blob/main/libs/utils/src/Platform-unix.cc#L82
it can be workaround by adding
`XInitThreads();
gdk_init(NULL, NULL);`
at the beginning of Platform::get_default_display_name()
It comes from
https://github.com/rcaelers/workrave/blob/main/ui/app/Application.cc#L91
but I think it should come after
https://github.com/rcaelers/workrave/blob/main/ui/app/Application.cc#L108
Because I believe GTK initialization happens just there.

The bug happens also on Mate Desktop 1.16 on an older system. Please fix it.

**Comment by rcaelers** [comment]
Should be fixed in v1.11.0.beta.6
