### ISSUE TITLE
Update does not work

### ISSUE THREAD

**Issue by Hillgrove** [rcaelers/workrave#497]
**Describe the bug**
Program pops up and asks to install update. When clicking button, nothing happens

**Expected behavior**
That it would install the update

 - Windows Version: 10
 - Workrave Version: 1.11.0 - beta5

**Comment by rcaelers** [comment]
Indeed. auto-update feature is still experimental. I fixed some issues in beta7, so the update from beta7 to beta8 should go smoother.
