### ISSUE TITLE
Workrave unexpected crash

### ISSUE THREAD

**Issue by timiji** [rcaelers/workrave#501]
**Describe the bug**
Exception: Workrave has unexpectedly crashed... Crash log saved... please file bug report...

**To Reproduce**
1. have not tried to reproduce error

**Expected behavior**
have never seen crash report before.
![Workrave_Screen](https://github.com/rcaelers/workrave/assets/140731802/68163bb7-057b-41ec-a67d-3a37bc1a1edf)
[workrave-crashlog.txt](https://github.com/rcaelers/workrave/files/12184979/workrave-crashlog.txt)

**Screenshots**

** Linux (please complete the following information in case you encountered the bug on Linux):**
 - Distribution: [e.g. Ubuntu, Fedora, Debian, ...] 
 - Distribution Version: 
 - Desktop Environment: [e.g. Gnome, KDE, XFCE, MATE, Cinnamon, ...]
 - Workrave Version [e.g. 1.10]

** Windows (please complete the following information in case you encountered the bug on Windows):
 - Windows Version: [ Windows 7, Windows 8, Windows 10]
 - Workrave Version [e.g. 1.10]

**Additional context**

**Comment by rcaelers** [comment]
Thanks for the crash log! Unfortunately, the crash log does not provide sufficient information to say what went wrong.
The crashlog is generated by Workrave 1.10. This version was released 10 years ago. Please check if the problem persists when using a more recent version (e.g. 1.10.51.1).

Please reopen if a newer version of Workrave still crashes.
