### ISSUE TITLE
Please set an icon for the window list button

### ISSUE THREAD

**Issue by davidhedlund** [rcaelers/workrave#502]
Screenshot from Ubuntu MATE 22.04. There's an icon for the Indicator Applet Complete (system tray in the top right), but there's no icon for the window list button (bottom left).

![Screenshot_ubuntu-mate-22 04 2-desktop-amd64 iso-clone_2023-08-01_12:28:18](https://github.com/rcaelers/workrave/assets/6416073/4181830e-883e-4643-b957-bf4c9aa6059c)

```
$ apt-cache show workrave
Package: workrave
Architecture: amd64
Version: 1.10.50-1
Priority: extra
Section: universe/gnome
Origin: Ubuntu
```

**Comment by rcaelers** [comment]
Apparently, this was already fixed in 1.11, I back ported the fix to 1.10.
