### ISSUE TITLE
Where Workrave preferences are stored?

### ISSUE THREAD

**Issue by KaKooDa** [rcaelers/workrave#506]
I can't find where are Workrave preferences are stored. By preferences I mean time between microbreaks, number of postpones and other settings which I've configured in Workrave. I looked up to .workrave directory and every other directory which had "workrave" name. But it is no where to be found.

**Comment by rcaelers** [comment]
On Windows, the settings are stored in the Windows registry (HKEY_LOCAL_USER\Sofware\Workrave).
On Linux, they are stored in dconf. You can use the dconf utility to access the settings (e.g. dconf dump /org/workrave/).
Alternatively, install dconf-editor and navigate to /org/workrave/

**Comment by rcaelers** [comment]
Closing issue. Let me know if you need further help.
