### ISSUE TITLE
zsh: segmentation fault (core dumped)  /usr/bin/workrave

### ISSUE THREAD

**Issue by hrqmonteiro** [rcaelers/workrave#522]
**Describe the bug**
`zsh: segmentation fault (core dumped)  /usr/bin/workrave`

**To Reproduce**
just try to open

**Expected behavior**
To open normally

**Screenshots**
![image](https://github.com/rcaelers/workrave/assets/17055027/64ea2ff9-4ea4-4dc3-8608-f4f400e94868)

** Linux (please complete the following information in case you encountered the bug on Linux):**
 - Distribution: Manjaro
 - Distribution Version: Latest
 - Desktop Environment: KDE
 - Workrave Version 

** Windows (please complete the following information in case you encountered the bug on Windows):
 - Windows Version: [ Windows 7, Windows 8, Windows 10]
 - Workrave Version: 1.10.52-3

**Additional context**
N/A

**Comment by ValdikSS** [comment]
`GDK_BACKEND="x11" workrave`

**Comment by rcaelers** [comment]
This crash is fixed in 1.11 beta 10
