### ISSUE TITLE
No tray icon on Wayland

### ISSUE THREAD

**Issue by cuihaoleo** [rcaelers/workrave#526]
**Describe the bug**
There is no icon when workrave runs on Wayland backend.

I think this is probably just not implemented. But as there is no specific issue on this, I'd like to open one.

**To Reproduce**
1. Run workrave on Wayland backend.

There is no tray icon.

**Expected behavior**
Tray icon shows up.

**Linux**

    Distribution: Arch Linux
    Distribution Version: rolling
    Desktop Environment: KDE Plasma 5.27.10, Wayland session
    Workrave Version: Beta 10 / Git HEAD (https://github.com/rcaelers/workrave/commit/330441054853c0c71c7830cc405c6681f95557f2)

**Additional context**

X11 backend (started by `GDK_BACKEND=x11 /usr/bin/workrave` ) will show the tray icon.

**Comment by rcaelers** [comment]
I have added support for tray icons using libappindicator, which supports [StatusNotifierItem](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/). This works out of the box on KDE with Wayland. I did not test GNOME Shell. I think an additional extension needs to be installed to support StatusNotifierItem.
This will be available in 1.11 beta 11

**Comment by cuihaoleo** [comment]
Thank you! I tested the git version on KDE and it seemed to work well. Now I'd say workrave is pretty much usable on Wayland.
