### ISSUE TITLE
Lack of automatic theme change

### ISSUE THREAD

**Issue by Favorass** [rcaelers/workrave#529]
**Describe the bug**
Lack of automatic theme change according to the system's one (only either "light" or "dark" option).

**Expected behavior**
Presence of it as it's a comfortable and modern standard feature that Workrave currently lacks.

**Windows (please complete the following information in case you encountered the bug on Windows):**
 - Windows Version: [ Windows 11 ]
 - Workrave Version [e.g. 1.11.0-beta.10]

**Additional context**
I'm not sure if I should have added this to "ideas" (https://github.com/rcaelers/workrave/discussions/530) in the "discussions" section or here.

**Comment by rcaelers** [comment]
Will be in the next 1.11 beta. Thanks for the suggestion.
