### ISSUE TITLE
Workrave is not compatible with GNOME Shell 46

### ISSUE THREAD

**Issue by jbicha** [rcaelers/workrave#532]
**Describe the bug**
I built workrave with `--enable-gnome45` and tweaked metadata.json to include "46". When I tried enabling the extension on GNOME Shell 46 Beta, I got this error in Extension Manager

```
Extension workrave@workrave.org: TypeError: this._box.add_actor is not a function

Stack trace:
  _init@file:///usr/share/gnome-shell/extensions/workrave@workrave.org/extension.js:185:17
  ButtonBox@resource:///org/gnome/shell/ui/panelMenu.js:13:1
  PanelMenuButton@resource:///org/gnome/shell/ui/panelMenu.js:99:4
  WorkraveButton@file:///usr/share/gnome-shell/extensions/workrave@workrave.org/extension.js:162:3
  enable@file:///usr/share/gnome-shell/extensions/workrave@workrave.org/extension.js:518:27
  _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:264:38
  async*_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:626:24
  _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:731:18
  createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730:46
  enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:287:29
  EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:453:38
  _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329:38
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  @resource:///org/gnome/shell/ui/init.js:21:20
```

**Other Info**
Here is documentation about some of the changes in GNOME Shell 46

https://gjs.guide/extensions/upgrading/gnome-shell-46.html

**Comment by rcaelers** [comment]
Should be fixed in beta11. Not yet in 1.10

**Comment by rcaelers** [comment]
Also committed to 1.10 (5a6d52478d95f08b6bc8f6ded5984dac94cd31bc)

**Comment by pieterdd** [comment]
Thank you for implementing the fix. Any indication as to when it will be released? Ubuntu LTS and Fedora ship with GNOME 46 now, so the fix would be a big help to those users.

**Comment by fmarier** [comment]
> Ubuntu LTS and Fedora ship with GNOME 46 now, so the fix would be a big help to those users.

The current Ubuntu LTS already has the required fixes: https://launchpad.net/ubuntu/+source/workrave/1.10.52-2ubuntu1

**Comment by pieterdd** [comment]
I see a [Fedora release](https://packages.fedoraproject.org/pkgs/workrave/workrave-gnome/fedora-40-updates.html) as well, and `1.10.52 - 4.fc40` is reported as installed on my machine, but the GNOME extension manager is still reporting the extension as incompatible :thinking: 

![image](https://github.com/rcaelers/workrave/assets/1407980/a9c49907-7b2c-4740-8af5-93ea3013cdd1)

**Comment by jbicha** [comment]
You need to report that issue to the Fedora maintainer.
