### ISSUE TITLE
Workrave applet suddenly no longer available in Ubuntu 22.04 Extensions

### ISSUE THREAD

**Issue by sitadrost** [rcaelers/workrave#535]
I've been using Workrave on Ubuntu 22.04 for several years now; installed it following [these instructions](https://askubuntu.com/a/967425), activated the applet that shows timers in the top bar through Extensions, and added Workrave to my Startup Applications. All worked fine, until about a week ago, when I noticed that Workrave no longer started at startup. Somehow it had disappeared from my Startup Applications. Also, I can no longer activate the Workrave applet that shows timers in the top bar, in Extensions the toggle button is greyed out (see attached screenshot).

Putting Workrave back  into my Startup Applications was simple enough, and seems to work so far (although I still don't understand why it disappeared in the first place), but I've no clue how to get the Workrave applet re-activated in Extensions.

I'm not sure whether this is related to Workrave or to Ubuntu (or Gnome, or ....), so I'm posting both here and on AskUbuntu. Any ideas as to what causes this, and how to fix it would be most appreciated!

EDIT: I'm using Extensions 42.9

![UbuntuExtensions](https://github.com/rcaelers/workrave/assets/45588365/7c1374d6-5b83-4c20-9235-09805bccc51d)

![GNOME_Extensions](https://github.com/rcaelers/workrave/assets/45588365/607b9278-861b-4ca6-8f3d-986f75669e05)

**Comment by sitadrost** [comment]
I've moved to an alternative application.

**Comment by smcvb** [comment]
> I've moved to an alternative application.

Would you mind sharing what this alternative application is, @sitadrost? Since moving to Ubuntu 22.04 I am experiencing several nuisances. So I figured trying something else would be smart.

**Comment by sitadrost** [comment]
Sure, I'm using [Stretchly](https://hovancik.net/stretchly/) now. It's not quite the same as Workrave, but so far, I'm perfectly happy with it.
