### ISSUE TITLE
Workrave still dies on wlroots compositors when break starts

### ISSUE THREAD

**Issue by jjramsey** [rcaelers/workrave#553]
Looks like https://github.com/rcaelers/workrave/issues/550 is not fixed just yet. I recompiled and tested Workrave after the pull request was merged, and I still see the same problem. Here's what I get when running Workrave with `WAYLAND_DEBUG=1`: [workrave-msgs-on-labwc3.txt](https://github.com/user-attachments/files/15997703/workrave-msgs-on-labwc3.txt)

As I said in a comment on the closed bug, the debug output *is* different; there is a `zwlr_layer_surface_v1#39.destroy()` there.

Unfortunately, I can't reopen the old bug, so I'm opening this one.

If you don't have the setup to test if a proposed fix solves this issue, please go ahead and ask me to do the test before closing it.

**Comment by vyivel** [comment]
Ah, I fixed only one instance of the problem…

Can you try https://github.com/rcaelers/workrave/pull/554?

**Comment by jjramsey** [comment]
> Ah, I fixed only one instance of the problem…
> 
> Can you try #554?

I will when I get the chance. I've got an eye exam this evening, so that may delay it.

**Comment by jjramsey** [comment]
Looks like Workrave is fully working on Labwc.

**Comment by jjramsey** [comment]
Looks like Workrave is fully working on Labwc.
