### ISSUE TITLE
The link in the About window does not work

### ISSUE THREAD

**Issue by Korb** [rcaelers/workrave#573]
**Describe the bug**
When I click on the www.workrave.org link, the About box displays a dialog box with the text

> Не удалось показать ссылку
> Не удалось выполнить вспомогательную программу (No such file or directory)
> Закрыть

what can be translated into English, how

> Failed to show link
> Failed to execute helper program (No such file or directory)
> Close

**To Reproduce**
1. Click on the "About" item in the context menu of the application in the system tray.
2. Click on www.workrave.org link
3. See error

**Expected behavior**
The web page https://workrave.org should open in browser

**Screenshots**
![2024-09-29_12-45-35](https://github.com/user-attachments/assets/ff98bf9b-aad8-407e-baa2-dcb9f0a013ee)

** Windows (please complete the following information in case you encountered the bug on Windows):
 - Microsoft Windows 10.0.19045.4957
 - Workrave 1.11.0-beta.14

**Additional context**
The default browser in the OS is Mozilla Firefox 131.0 (64-bit)

**Comment by rcaelers** [comment]
It seems this helper is either gspawn-win64-helper-console.exe, or gspawn-win64-helper.exe. I will add them in beta.15

**Comment by rcaelers** [comment]
Will be fixed in beta.15
