### ISSUE TITLE
The exercises are displayed in English, although the Russian interface language is selected in the application settings

### ISSUE THREAD

**Issue by Korb** [rcaelers/workrave#574]
**Describe the bug**
Subj. Despite the fact that there is a translation into Russian of all exercises in the file "\share\exercises\exercises.xml".

**To Reproduce**
1. Go to Preferences / User interface / General
2. Select "Russian / Русский" from the Language drop-down list
3. Click Close
4. Click on the "Перерыв на отдых" item in the context menu of the application in the system tray.
5. Make sure the exercise description is displayed in English.

**Expected behavior**

**Screenshots**
![2024-09-29_13-14-51](https://github.com/user-attachments/assets/e416b91d-0603-46a9-9142-063ebb1e5628)

![2024-09-29_13-14-13 2](https://github.com/user-attachments/assets/f73b456e-debf-4bc8-931d-0e543ae7f74c)

** Windows (please complete the following information in case you encountered the bug on Windows):
 - Microsoft Windows 10.0.19045.4957
 - Workrave 1.11.0-beta.14

**Comment by rcaelers** [comment]
Indeed. Will be fixed in beta.15.
