### ISSUE TITLE
Segfault on Ubuntu 17.10 with Intel Graphics

### ISSUE THREAD

**Issue by KarunaGovind** [rcaelers/workrave#88]
Hi. Workrave v1_10_20  segfaults on Ubuntu 17.10 (Gnome Shell). It works fine when using my Nvidia card, but crashes while on Intel integrated graphics (prime-select). Tried both modes (after reboots) and problem can be replicated.

dmesg output:
`[Tue Nov  7 01:04:11 2017] workrave[5440]: segfault at 0 ip 00007f2471d013ce sp 00007fff4a133560 error 4 in libX11.so.6.3.0[7f2471cc4000+134000]
`

I can email you the crash log if you like.

Thanks.

**Comment by KarunaGovind** [comment]
Works if I do:
` workrave --display=:0`

I can live with that for now.

**Comment by rubo77** [comment]
That seems to work, but how do you enter the settings?

**Comment by KarunaGovind** [comment]
@rubo77 Do you mean you'd like to make it permanent? What I did for now:

`cp /usr/share/applications/workrave.desktop ~/.local/share/applications/`

Then, I edited the "Exec" command in  ~/.local/share/applications/workrave.desktop. Unfortunately, I don't have the time to look at the source for workrave but hopefully someone else can do it. 

So far that works perfectly. No crashes and I get timely notifications also.

**Comment by rubo77** [comment]
I would ike to edit the time preferences, get a micro break every 15minutes for 10 seconds.

I cannot enter the preferences nowhere to change the settings

**Comment by KarunaGovind** [comment]
@rubo77 , install gnome-tweak-tool. Then install this extension: https://extensions.gnome.org/extension/495/topicons/

If that doesn't work, then try this - https://extensions.gnome.org/extension/1031/topicons/

**Comment by seifsg** [comment]
>I would ike to edit the time preferences, get a micro break every 15minutes for 10 seconds.
>I cannot enter the preferences nowhere to change the settings.
>there is no top menu and no icon in the top-bar or so

@rubo77 that's an issue actually.

**Comment by rubo77** [comment]
@KarunaGovind: why is this closed, if it is not fixed?

(To have a Workaround in an **open** issue is a good thing though.)

**Comment by KarunaGovind** [comment]
@rubo77, feel free to open it. I probably (incorrectly) assumed it was something you guys might have been aware of (thought it might have been the Wayland issue in release notes). 

So far it works fairly well on my Wayland (Ubuntu 17.10 with Gnome Shell).

**Comment by rubo77** [comment]
It only works well, if you Fix the legacy tray icons:

## Workaround: Install Topicons Plus
from https://extensions.gnome.org/extension/1031/topicons/  
or install manually with:

            sudo apt install gnome-tweak-tool make
            cd /tmp
            git clone https://github.com/phocean/TopIcons-plus.git
            cd TopIcons-plus
            sudo make install INSTALL_PATH=/usr/share/gnome-shell/extensions

Now, reload GNOME Shell. You can either hit **Alt+F2**, type **r**, and hit **enter** (or login/logout). Finally, launch the `gnome-tweak-tool` utility (german: "Optimierungen") to manage extensions. There, you can enable **TopIcons Plus** and then tweak its look and feel.

----

maybe this should be added to the readme?
