### ISSUE TITLE
Two icons and two empty icons

### ISSUE THREAD

**Issue by hannob** [rcaelers/workrave#90]
I'm getting multiple icons for workrave in my tray. I'm using LXDE on Gentoo.

There are two workrave icons in the tray left of the wifi symbol and two "empty" icons right of the wifi symbol.

Any idea what's going wrong there? Attaching an image to show how it looks:
![workrave-icon-bug](https://user-images.githubusercontent.com/990588/32938220-bcc44112-cb7b-11e7-8721-6bc61bbd631f.png)

**Comment by timo** [comment]
Similar problem in xfce4, with one of the icons being slightly offset
![workrave](https://user-images.githubusercontent.com/25167/34340794-edde3a5a-e98a-11e7-9d88-3ba6e2dba3f6.png)

**Comment by rubo77** [comment]
Same issue on plain Ubuntu 17.10

**Comment by kosciak9** [comment]
Same thing on Arch Linux with newest packages. After closing Workrave whitespace persists.
![2018-08-17-232729_112x52_scrot](https://user-images.githubusercontent.com/4347034/44289558-1c089d00-a275-11e8-93e6-438ac4d2e7c2.png)
![2018-08-17-232716_95x43_scrot](https://user-images.githubusercontent.com/4347034/44289562-1e6af700-a275-11e8-855b-c78aa4520ae9.png)

**Comment by andyboeh** [comment]
Just follow the instructions for Cinnamon in #118: Explicitly add the workrave applet to the panel, then enable the panel in workrave. This fixed it for me on Xfce.

**Comment by johnnyasantoss** [comment]
To me it only shows duplicates when the applet option is on.

**Comment by Xerus2000** [comment]
Same thing on KDE Plasma - fixed by turning the applet option off

**Comment by rcaelers** [comment]
This should be fixed in Workrave 1.10.45 (to be release). See  #258 for more information
