### ISSUE TITLE
Can't download from sourceforge because of sanction

### ISSUE THREAD

**Issue by mort3za** [rcaelers/workrave#91]
Hi and thanks for the great work!  

When I want to download workrave tarball, I see "Download Forbidden" message (because of US sanctions against Iran).
Can you please use another service for downloading the software in workrave.com?
Or change your sourceforge account settings to allow everyone to download it (If i'm not wrong about that settings).

Thanks again :)

**Comment by rcaelers** [comment]
Hi,

I didn’t know you could configure that in sourceforfe.
Perhaps you can download Workrave from github: https://github.com/rcaelers/workrave/releases/tag/v1_10_1 <https://github.com/rcaelers/workrave/releases/tag/v1_10_1>

Kind regards
  Rob

**Comment by szpak** [comment]
I don't know if it is still available, but a few years ago it was possible to disable that restriction per project by its admin/owner:
https://sourceforge.net/blog/some-good-news-sourceforge-removes-blanket-blocking/

**Comment by rcaelers** [comment]
Workrave is now automatically published on Github when a new release is made. Website will be updated at a later time.
