### ISSUE TITLE
Applet not appearing in Ubuntu 17.04

### ISSUE THREAD

**Issue by ethantkoenig** [rcaelers/workrave#92]
I recently installed workrave on Ubuntu 17.04 (via the `rob-caelers/workrave` PPA). However, the applet did not show in the task bar, and as a result I was unable to access the settings/preferences.

I was able to fix the solution by following https://askubuntu.com/questions/766601/workrave-applet-blank-in-ubuntu-16-04:
1. `sudo apt install workrave-data workrave-unity`
2. `unity --replace`

In order to make life easier for future Ubuntu users, could you please document these steps somewhere (e.g. `README.md`, http://workrave.org)?

**Comment by pabloab** [comment]
So even [man page](http://manpages.ubuntu.com/manpages/xenial/en/man1/unity.1.html) say _Deprecated option for backwards compatibility.  Has no effect._ this [force Unity to reload menu data](https://askubuntu.com/a/339780/349837)? Seems a long standing bug on [Ubuntu ](https://bugs.launchpad.net/ubuntu/+source/workrave/+bug/796824) and [Debian KDE](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829450).

**Comment by chefwen** [comment]
On Ubuntu 16.04 I tried the commands above, then the unity top bar just disappeared, I tried all the methods I searched on 'Ubuntu top bar diappeared ', reinstall ubuntudesktop, reset unity, etc. none of them worked. But then I uninstall workrave related packages and run unity --replace again, I got the top bar back! Hope this message will help someone who met the same problem.

**Comment by rcaelers** [comment]
Workrave now has documentation on its website, including documentation for all applets. So I could add this information there. However, Canonical has abandoned Unity, so I think it is safe to close this issue now. 

If you think it is still valuable to document this, then a pull request for the workrave-website repository would be appreciated (I don't have/use/test Unity any more myself).
