### ISSUE TITLE
Support for Wayland

### ISSUE THREAD

**Issue by Dzordzu** [rcaelers/workrave#94]
Will Wayland be supported (Ubuntu 17.10)?

**Comment by rubo77** [comment]
https://github.com/rcaelers/workrave/issues/88

**Comment by rcaelers** [comment]
Workrave supports Wayland to a certain extend. Unfortunately, the API wayland offer is not really suitable for application that want to take control over keyboard/mouse/screen like Workrave.

**Comment by maricn** [comment]
#88 explains how to deal with it on Gnome, but there are two issues i'm experiencing on another Wayland composer - SwayWM:

1. I can't open settings/preferences. Whenever I click on it a segmentation fault happens and the app crashes.
2. There is no tray icon for the app.

I'm on:
```bash
$ uname -ora
Linux work-x1c-arch 5.11.14-arch1-1 #1 SMP PREEMPT Wed, 14 Apr 2021 12:06:34 +0000 x86_64 GNU/Linux

$ sway --version
sway version 1.6

# using package (AUR)
workrave-next-gtk3-git v1_10_16.r644.7ede0462-2

# startup command
workrave --display="$DISPLAY"
```

**Comment by azzamsa** [comment]
@maricn is using `workrave --display="$DISPLAY"` solves all the issue?
I plan to migrate to wayland.

**Comment by maricn** [comment]
> @maricn is using `workrave --display="$DISPLAY"` solves all the issue?
> I plan to migrate to wayland.

For me it only solves starting the app, but it's still unusable. Perhaps I haven't set it up fully yet, but I couldn't find further info on how to make it work fully. I reverted to using https://github.com/ActivityWatch/activitywatch for tracking my time, but didn't really look deeply for anything focused on RSI specifically.

**Comment by azzamsa** [comment]
Thanks for the info. I should cancel my migration plan then.

**Comment by anarcat** [comment]
i've been looking at this problem as well, and it seems like the only wayland-specific RSI app is KDE's [rsibreak](https://invent.kde.org/utilities/rsibreak)

**Comment by ValdikSS** [comment]
> i've been looking at this problem as well, and it seems like the only wayland-specific RSI app is KDE's [rsibreak](https://invent.kde.org/utilities/rsibreak)

And it's totally broken on Wayland unfortunately.
https://bugs.kde.org/show_bug.cgi?id=422033
